#!/bin/bash
set -e


TMP=${TMP:-/tmp/work}
LOG=${LOG:-$HOME/logs/stage2}
SRC=${SRC:-/sources}

name=texinfo
version=6.7

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/$name-$version.tar.xz -C $TMP

{ time \
   {

    cd $TMP/$name-$version

    ./configure --prefix=/usr

    make
    
    make install
    
    }
} 2>&1 | tee $name.log

[ $PIPESTATUS = 0 ] && mv $name.log $LOG || exit $PIPESTATUS

rm -fr $TMP
