#!/bin/bash
set -e


TMP=${TMP:-/tmp}
LOG=${LOG:-$HOME/logs/stage2}
SRC=${SRC:-$/sources}

name=gettext
version=0.21

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/$name-$version.tar.xz -C $TMP

{ time \
   {

    cd $TMP/$name-$version

    ./configure --disable-shared

    make
    
    cp -v gettext-tools/src/{msgfmt,msgmerge,xgettext} /usr/bin

    }
} 2>&1 | tee $name.log

[ $PIPESTATUS = 0 ] && mv $name.log $LOG || exit $PIPESTATUS

rm -fr $TMP
