#!/bin/bash
set -e


TMP=${TMP:-$(dirname $0)/Build-TMP}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-$/sources}

pkgname=libstdc++-gcc-pass2
pkgver=10.2.0

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/gcc-$pkgver.tar.xz -C $TMP

{ time \
   {

    cd $TMP/gcc-$pkgver
    ln -s gthr-posix.h libgcc/gthr-default.h
    mkdir -v build
    cd       build
    ../libstdc++-v3/configure                \
        CXXFLAGS="-g -O2 -D_GNU_SOURCE"      \
        --prefix=/usr                        \
        --disable-multilib                   \
        --disable-nls                        \
        --host=$(uname -m)-lfs-linux-gnu     \
        --disable-libstdcxx-pch
    make
    make install
    
    }
} 2>&1 | tee $pkgname.log

[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
