#!/bin/bash
set -e


TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-$/sources}

pkgname=perl
pkgver=5.32.0

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/$pkgname-$pkgver.tar.xz -C $TMP

{ time \
   {

    cd $TMP/$pkgname-$pkgver
    sh Configure -des                                                \
                 -Dprefix=/usr                                       \
                 -Dvendorprefix=/usr                                 \
                 -Dprivlib=/usr/lib/perl5/${pkgver::4}/core_perl     \
                 -Darchlib=/usr/lib/perl5/${pkgver::4}/core_perl     \
                 -Dsitelib=/usr/lib/perl5/${pkgver::4}/site_perl     \
                 -Dsitearch=/usr/lib/perl5/${pkgver::4}/site_perl    \
                 -Dvendorlib=/usr/lib/perl5/${pkgver::4}/vendor_perl \
                 -Dvendorarch=/usr/lib/perl5/${pkgver::4}/vendor_perl
    make
    make install

    }
} 2>&1 | tee $pkgname.log

[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
