#!/bin/bash
set -e


TMP=${TMP:-/tmp}
LOG=${LOG:-$HOME/logs/stage2}
SRC=${SRC:-$/sources}

pkgname=python
pkgver=3.9.1

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/Python-$pkgver.tar.xz -C $TMP

{ time \
   {

    cd $TMP/Python-$pkgver

	./configure --prefix=/usr   \
	            --enable-shared \
	            --without-ensurepip

    make
    
    make install
    
    }
} 2>&1 | tee $pkgname.log

[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
