#!/bin/bash 
set -e

TMP=${TMP:-$/tmp}
LOG=${LOG:-$HOME/logs/stage3}
SRC=${SRC:-/sources}

pkgname=bc
pkgver=3.2.5

mkdir -p $TMP $LOG

tar xf $SRC/$pkgname-$pkgver.tar.xz -C $TMP

{ time \
   {

    cd $TMP/$pkgname-$pkgver

	sed -i '612d' configure.sh

	PREFIX=/usr CC=gcc ./configure.sh -G -O3

    make

    make install

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
