#!/bin/bash 
set -e

TMP=${TMP:-$/tmp}
LOG=${LOG:-$HOME/logs/stage3}
SRC=${SRC:-/sources}

pkgname=e2fsprogs
pkgver=1.45.6

mkdir -p $TMP $LOG

tar xf $SRC/$pkgname-$pkgver.tar.gz -C $TMP

{ time \
   {

    cd $TMP/$pkgname-$pkgver
    
    mkdir -v build
    cd       build

	../configure --prefix=/usr           \
				 --bindir=/bin           \
				 --with-root-prefix=""   \
				 --enable-elf-shlibs     \
				 --disable-libblkid      \
				 --disable-libuuid       \
				 --disable-uuidd         \
				 --disable-fsck
    
    make
    
    make install
    
	chmod -v u+w /usr/lib/{libcom_err,libe2p,libext2fs,libss}.a
		
	gunzip -v /usr/share/info/libext2fs.info.gz
	install-info --dir-file=/usr/share/info/dir /usr/share/info/libext2fs.info

	makeinfo -o      doc/com_err.info ../lib/et/com_err.texinfo
	install -v -m644 doc/com_err.info /usr/share/info
	install-info --dir-file=/usr/share/info/dir /usr/share/info/com_err.info

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
