#!/bin/bash 
set -e

TMP=${TMP:-$/tmp}
LOG=${LOG:-$HOME/logs/stage3}
SRC=${SRC:-/sources}

pkgname=elfutils
pkgver=0.182

mkdir -p $TMP $LOG

tar xf $SRC/$pkgname-$pkgver.tar.bz2 -C $TMP

{ time \
   {

    cd $TMP/$pkgname-$pkgver
    
	./configure --prefix=/usr                \
	            --disable-debuginfod         \
	            --enable-libdebuginfod=dummy \
	            --libdir=/lib
    
    make
    
	make -C libelf install
	install -vm644 config/libelf.pc /usr/lib/pkgconfig
	rm /lib/libelf.a

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
