#!/bin/bash 
set -e

TMP=${TMP:-$/tmp}
LOG=${LOG:-$HOME/logs/stage3}
SRC=${SRC:-/sources}

pkgname=expect
pkgver=5.45.4

mkdir -p $TMP $LOG

tar xf $SRC/$pkgname$pkgver.tar.gz -C $TMP

{ time \
   {

    cd $TMP/$pkgname$pkgver
    
    ./configure --prefix=/usr           \
                --with-tcl=/usr/lib     \
                --enable-shared         \
                --mandir=/usr/share/man \
                --with-tclinclude=/usr/include
 
    make

    make install
    ln -svf expect$pkgver/libexpect$pkgver.so /usr/lib

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
