#!/bin/bash 
set -e

TMP=${TMP:-$/tmp}
LOG=${LOG:-$HOME/logs/stage3}
SRC=${SRC:-/sources}

pkgname=gawk
pkgver=5.1.0

mkdir -p $TMP $LOG

tar xf $SRC/$pkgname-$pkgver.tar.xz -C $TMP

{ time \
   {

    cd $TMP/$pkgname-$pkgver
    
    sed -i 's/extras//' Makefile.inn
    
    ./configure --prefix=/usr
    
    make
    
    make install
    
    mkdir -v /usr/share/doc/$pkgname-$pkgver
    cp    -v doc/{awkforai.txt,*.{eps,pdf,jpg}} /usr/share/doc/$pkgname-$pkgver

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
