#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/sources}

pkgname=gettext
pkgver=0.21

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/$pkgname-$pkgver.tar.xz -C $TMP

{ time \
   {

    cd $TMP/$pkgname-$pkgver
    
    ./configure --prefix=/usr    \
                --disable-static \
                --docdir=/usr/share/doc/$pkgname-$pkgver
    
    make
    
    make install
    chmod -v 0755 /usr/lib/preloadable_libintl.so

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
