#!/bin/bash 
set -e

TMP=${TMP:-$/tmp}
LOG=${LOG:-$HOME/logs/stage3}
SRC=${SRC:-/sources}

pkgname=intltool
pkgver=0.51.0

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/$pkgname-$pkgver.tar.gz -C $TMP

{ time \
   {

    cd $TMP/$pkgname-$pkgver
    
    sed -i 's:\\\${:\\\$\\{:' intltool-update.in
    
    ./configure --prefix=/usr
    
    make
    
    make install
    install -v -Dm644 doc/I18N-HOWTO /usr/share/doc/$pkgname-$pkgver/I18N-HOWTO

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
