#!/bin/bash 
set -e

TMP=${TMP:-$/tmp}
LOG=${LOG:-$HOME/logs/stage3}
SRC=${SRC:-/sources}

name=iproute2
version=5.10.0

mkdir -p $TMP $LOG

tar xf $SRC/$name-$version.tar.xz -C $TMP

{ time \
   {

    cd $TMP/$name-$version
    
	sed -i /ARPD/d Makefile
	rm -fv man/man8/arpd.8

	sed -i 's/.m_ipt.o//' tc/Makefile
    
    make
    
    make DOCDIR=/usr/share/doc/$name-$version install

    }
} 2>&1 | tee $name.log
    
[ $PIPESTATUS = 0 ] && mv $name.log $LOG || exit $PIPESTATUS

rm -fr $TMP
