#!/bin/bash 
set -e

TMP=${TMP:-$/tmp}
LOG=${LOG:-$HOME/logs/stage3}
SRC=${SRC:-/sources}

pkgname=kbd
pkgver=2.4.0

mkdir -p $TMP $LOG

tar xf $SRC/$pkgname-$pkgver.tar.xz -C $TMP

{ time \
   {

    cd $TMP/$pkgname-$pkgver
    
    patch -Np1 -i $SRC/$pkgname-$pkgver-backspace-1.patch
        
	sed -i '/RESIZECONS_PROGS=/s/yes/no/' configure
	sed -i 's/resizecons.8 //' docs/man/man8/Makefile.in

	./configure --prefix=/usr --disable-vlock
    
    make
    
    make install

    rm -v /usr/lib/libtswrap.{a,la,so*}

    mkdir -v            /usr/share/doc/$pkgname-$pkgver
    cp -R -v docs/doc/* /usr/share/doc/$pkgname-$pkgver

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
