#!/bin/bash 
set -e

TMP=${TMP:-$/tmp}
LOG=${LOG:-$HOME/logs/stage3}
SRC=${SRC:-/sources}

pkgname=libcap
pkgver=2.47

mkdir -p $TMP $LOG

tar xf $SRC/$pkgname-$pkgver.tar.xz -C $TMP

{ time \
   {

    cd $TMP/$pkgname-$pkgver
    
    sed -i '/install -m.*STA/d' libcap/Makefile
    
    make prefix=/usr lib=lib
    
    make prefix=/usr lib=lib install
    for libname in cap psx; do
        mv -v /usr/lib/lib${libname}.so.* /lib
        ln -sfv ../../lib/lib${libname}.so.2 /usr/lib/lib${libname}.so
        chmod -v 755 /lib/lib${libname}.so.${pkgver}
    done

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
