#!/bin/bash 
set -e

TMP=${TMP:-$/tmp}
LOG=${LOG:-$HOME/logs/stage3}
SRC=${SRC:-/sources}

pkgname=python3
pkgver=3.9.0

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/Python-$pkgver.tar.xz -C $TMP

{ time \
   {

    cd $TMP/Python-$pkgver
    
    ./configure --prefix=/usr       \
                --enable-shared     \
                --with-system-expat \
                --with-system-ffi   \
                --with-ensurepip=yes
    
    make
    
    make install
    chmod -v 755 /usr/lib/libpython${pkgver:0:3}.so
    chmod -v 755 /usr/lib/libpython3.so
    ln -sfv pip${pkgver:0:3} /usr/bin/pip3

    install -v -dm755 /usr/share/doc/python-$pkgver/html 

    tar --strip-components=1  \
        --no-same-owner       \
        --no-same-permissions \
        -C /usr/share/doc/python-$pkgver/html \
        -xvf $SRC/python-$pkgver-docs-html.tar.bz2

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
