#!/bin/bash 
set -e

TMP=${TMP:-$/tmp}
LOG=${LOG:-$HOME/logs/stage3}
SRC=${SRC:-/sources}

name=texinfo
version=6.7

mkdir -p $TMP $LOG

tar xf $SRC/$name-$version.tar.xz -C $TMP

{ time \
   {

    cd $TMP/$name-$version
    
    ./configure --prefix=/usr --disable-static
    
    make
    
    make install

	make TEXMF=/usr/share/texmf install-tex
    
	pushd /usr/share/info
	  rm -v dir
	  for f in *
	    do install-info $f dir 2>/dev/null
	  done
	popd

    }
} 2>&1 | tee $name.log
    
[ $PIPESTATUS = 0 ] && mv $name.log $LOG || exit $PIPESTATUS

rm -fr $TMP
