#!/bin/bash 
set -e

TMP=${TMP:-$/tmp}
LOG=${LOG:-$HOME/logs/stage3}
SRC=${SRC:-/sources}

pkgname=xml-parser
pkgver=2.46

mkdir -p $TMP $LOG

tar xf $SRC/XML-Parser-$pkgver.tar.gz -C $TMP

{ time \
   {

    cd $TMP/XML-Parser-$pkgver
    
    perl Makefile.PL

    make

    make install

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
