#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/sources}

pkgname=xml-parser
pkgver=2.46

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/XML-Parser-$pkgver.tar.gz -C $TMP

{ time \
   {

    cd $TMP/XML-Parser-$pkgver
    
    perl Makefile.PL

    make

    make install

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
