#!/bin/bash 
set -e

TMP=${TMP:-$/tmp}
LOG=${LOG:-$HOME/logs/stage3}
SRC=${SRC:-/sources}

pkgname=zlib
pkgver=1.2.11

mkdir -p $TMP $LOG

tar xf $SRC/$pkgname-$pkgver.tar.xz -C $TMP

{ time \
   {

    cd $TMP/$pkgname-$pkgver
    
    ./configure --prefix=/usr
    
    make
    
    make install
    
	mv -v /usr/lib/libz.so.* /lib
	ln -sfv ../../lib/$(readlink /usr/lib/libz.so) /usr/lib/libz.so.so

	rm -fv /usr/lib/libz.a

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
