#!/bin/bash -e


TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgbase=Iana-Etc-20200429
pkgname=iana-etc
pkgver=20200429

rm -fr $TMP
mkdir -p $TMP $LOG $SRC $(dirname $0)/build

tar xf $SRC/$pkgname-$pkgver.tar.gz -C $TMP

{ time \
   {

    cd $TMP/$pkgname-$pkgver
    
    cp -v services protocols /etc

    }
} 2>&1 | tee $LOG/$pkgbase.log
    
[ $PIPESTATUS = 0 ] && echo "$pkgname-$pkgver" > $(dirname $0)/build/$pkgbase || exit $PIPESTATUS

rm -fr $TMP
