#!/bin/bash -e


TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources/lfs}

pkgbase=Systemd-245
pkgname=systemd
pkgver=245

rm -fr $TMP
mkdir -p $TMP $LOG $SRC $(dirname $0)/build

tar xf $SRC/$pkgname-$pkgver.tar.gz -C $TMP

{ time \
   {

    cd $TMP/$pkgname-$pkgver
    
    patch -Np1 -i $SRC/$pkgname-$pkgver-gcc_10-fixes-2.patch
    
    ln -sf /bin/true /usr/bin/xsltproc
    
    tar -xf $SRC/systemd-man-pages-$pkgver.tar.xz
    
    sed '179,$ d' -i src/resolve/meson.build
    
    sed -i 's/GROUP="render", //' rules.d/50-udev-default.rules.in
    
    mkdir -p build
    cd       build

    LANG=en_US.UTF-8                    \
    meson --prefix=/usr                 \
          --sysconfdir=/etc             \
          --localstatedir=/var          \
          -Dblkid=true                  \
          -Dbuildtype=release           \
          -Ddefault-dnssec=no           \
          -Dfirstboot=false             \
          -Dinstall-tests=false         \
          -Dkmod-path=/bin/kmod         \
          -Dldconfig=false              \
          -Dmount-path=/bin/mount       \
          -Drootprefix=                 \
          -Drootlibdir=/lib             \
          -Dsplit-usr=true              \
          -Dsulogin-path=/sbin/sulogin  \
          -Dsysusers=false              \
          -Dumount-path=/bin/umount     \
          -Db_lto=false                 \
          -Drpmmacrosdir=no             \
          -Dhomed=false                 \
          -Duserdb=false                \
          -Dman=true                    \
          ..
    
    LANG=en_US.UTF-8 ninja
    
    LANG=en_US.UTF-8 ninja install
    
    rm -f /usr/bin/xsltproc
    
    systemd-machine-id-setup
    
    systemctl preset-all
    
    systemctl disable systemd-time-wait-sync.service
    
    rm -f /usr/lib/sysctl.d/50-pid-max.conf
    

    }
} 2>&1 | tee $LOG/$pkgbase.log
    
[ $PIPESTATUS = 0 ] && echo "$pkgname-$pkgver" > $(dirname $0)/build/$pkgbase || exit $PIPESTATUS

rm -fr $TMP
