#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=asciidoc
pkgver=9.0.4

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/$pkgname-$pkgver.tar.* -C $TMP

{ time \
   {

    cd $TMP/$pkgname-$pkgver

    sed -i 's:doc/testasciidoc.1::' Makefile.in
    rm doc/testasciidoc.1.txt

    ./configure --prefix=/usr     \
                --sysconfdir=/etc \
                --docdir=/usr/share/doc/$pkgname-$pkgver
    make

    make install
    make docs

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
