#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=autoconf213
pkgver=2.13

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/autoconf-$pkgver.tar.* -C $TMP

{ time \
   {

    cd $TMP/autoconf-$pkgver
    patch -Np1 -i $SRC/autoconf-$pkgver-consolidated_fixes-1.patch
    mv -v autoconf.texi autoconf${pkgver//./}.texi                     
    rm -v autoconf.info                                      
    ./configure --prefix=/usr --program-suffix=2.13          
    make

    make install                                     
    install -v -m644 autoconf${pkgver//./}.info /usr/share/info
    install-info --info-dir=/usr/share/info autoconf${pkgver//./}.info
    
    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
