#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=boost
pkgver=1.74.0

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/${pkgname}_${pkgver//./_}.tar.bz2 -C $TMP

{ time \
   {

    cd $TMP/${pkgname}_${pkgver//./_}

    ./bootstrap.sh --prefix=/usr --with-python=python3 --with-icu
    ./b2 stage -j$(nproc) threading=multi link=shared

    ./b2 install threading=multi link=shared

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
