#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=cdparanoia
pkgver=10.2

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/cdparanoia-III-$pkgver.src.tgz -C $TMP

{ time \
   {

    cd $TMP/cdparanoia-III-$pkgver

    patch -Np1 -i $SRC/cdparanoia-III-$pkgver-gcc_fixes-1.patch
    ./configure --prefix=/usr --mandir=/usr/share/man
    make -j1

    make install
    chmod -v 755 /usr/lib/libcdda_*.so.0.$pkgver

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
