#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=cpio
pkgver=2.13

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/$pkgname-$pkgver.tar.* -C $TMP

{ time \
   {

   cd $TMP/$pkgname-$pkgver

    sed -i '/The name/,+2 d' src/global.c

    ./configure --prefix=/usr \
                --bindir=/bin \
                --enable-mt   \
                --with-rmt=/usr/libexec/rmt
    make
    makeinfo --html            -o doc/html      doc/cpio.texi
    makeinfo --html --no-split -o doc/cpio.html doc/cpio.texi
    makeinfo --plaintext       -o doc/cpio.txt  doc/cpio.texi

    make install
    install -v -m755 -d /usr/share/doc/$pkgname-$pkgver/html
    install -v -m644    doc/html/* \
                        /usr/share/doc/$pkgname-$pkgver/html
    install -v -m644    doc/cpio.{html,txt} \
                        /usr/share/doc/$pkgname-$pkgver

   }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
