#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=cracklib
pkgver=2.9.7

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/$pkgname-$pkgver.tar.* -C $TMP

{ time \
   {

    cd $TMP/$pkgname-$pkgver

    sed -i '/skipping/d' util/packer.c

    ./configure --prefix=/usr    \
                --disable-static \
                --with-default-dict=/lib/cracklib/pw_dict 
    make

    make install                      
    mv -v /usr/lib/libcrack.so.* /lib 
    ln -sfv ../../lib/$(readlink /usr/lib/libcrack.so) /usr/lib/libcrack.so

    install -v -m644 -D      $SRC/cracklib-words-$pkgver.bz2 \
                            /usr/share/dict/cracklib-words.bz2    

    bunzip2 -v               /usr/share/dict/cracklib-words.bz2    
    ln -v -sf cracklib-words /usr/share/dict/words                 
    echo "beginning" >>      /usr/share/dict/cracklib-extra-words
    install -v -m755 -d      /lib/cracklib                         

    create-cracklib-dict     /usr/share/dict/cracklib-words \
                            /usr/share/dict/cracklib-extra-words

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
