#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=cups
pkgver=$pkgver

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/$pkgname-$pkgver.tar.* -C $TMP

{ time \
   {

    cd $TMP/$pkgname-$pkgver

    useradd -c "Print Service User" -d /var/spool/cups -g lp -s /bin/false -u 9 lp

    groupadd -g 19 lpadmin

    sed -i '/stat.h/a #include <asm-generic/ioctls.h>' tools/ipptool.c

    CC=gcc CXX=g++ \
    ./configure --libdir=/usr/lib            \
                --with-rcdir=/tmp/cupsinit   \
                --with-system-groups=lpadmin \
                --with-docdir=/usr/share/cups/doc-$pkgver --disable-libusb --enable-libpaper
    make

    make install
    rm -rf /tmp/cupsinit
    ln -svnf ../cups/doc-$pkgver /usr/share/doc/cups-$pkgver

    echo "ServerName /run/cups/cups.sock" > /etc/cups/client.conf

    gtk-update-icon-cache -qtf /usr/share/icons/hicolor

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
