#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=dbus
pkgver=1.12.20

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/$pkgname-$pkgver.tar.* -C $TMP

{ time \
   {

    cd $TMP/$pkgname-$pkgver

          ./configure --prefix=/usr                        \
                  --sysconfdir=/etc                    \
                  --localstatedir=/var                 \
                  --enable-user-session                \
                  --disable-doxygen-docs               \
                  --disable-xml-docs                   \
                  --disable-static                     \
                  --docdir=/usr/share/doc/$pkgname-$pkgver \
                  --with-console-auth-dir=/run/console \
                  --with-system-pid-file=/run/dbus/pid \
                  --with-system-socket=/run/dbus/system_bus_socket
      make

      make install

      mv -v /usr/lib/libdbus-1.so.* /lib
      ln -sfv ../../lib/$(readlink /usr/lib/libdbus-1.so) /usr/lib/libdbus-1.so

      chown -v root:messagebus /usr/libexec/dbus-daemon-launch-helper
      chmod -v      4750       /usr/libexec/dbus-daemon-launch-helper

      cat > /etc/dbus-1/session-local.conf << "EOF"
<!DOCTYPE busconfig PUBLIC
 "-//freedesktop//DTD D-BUS Bus Configuration 1.0//EN"
 "http://www.freedesktop.org/standards/dbus/1.0/busconfig.dtd">
<busconfig>

  <!-- Search for .service files in /usr/local -->
  <servicedir>/usr/local/share/dbus-1/services</servicedir>

</busconfig>
EOF

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
