#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=dbus-glib
pkgver=0.110

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/$pkgname-$pkgver.tar.* -C $TMP

{ time \
   {

    cd $TMP/$pkgname-$pkgver

      ./configure --prefix=/usr     \
                  --sysconfdir=/etc \
                  --disable-static --enable-gtk-doc
      make

      make install

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
