#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=dejavu-fonts-ttf
pkgver=2.37

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/$pkgname-$pkgver.tar.* -C $TMP

{ time \
   {

   cd $TMP/$pkgname-$pkgver

    install -v -d -m755 /usr/share/fonts/dejavu
    install -v -m644 ttf/*.ttf /usr/share/fonts/dejavu
    fc-cache -v /usr/share/fonts/dejavu

   }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
