#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=desktop-file-utils
pkgver=0.26

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/$pkgname-$pkgver.tar.* -C $TMP

{ time \
   {

    cd $TMP/$pkgname-$pkgver

   rm -fv /usr/bin/desktop-file-edit
   
   mkdir build
   cd    build

   meson --prefix=/usr ..
   ninja
   
   ninja install
   
   install -vdm755 /usr/share/applications
   update-desktop-database /usr/share/applications

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
