#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=docbook-xml
pkgver=4.5

rm -fr $TMP
mkdir -p $TMP/$pkgname-$pkgver $LOG

unzip -d $TMP $SRC/$pkgname-$pkgver.zip

{ time \
   {

    cd $TMP/$pkgname-$pkgver

    nstall -v -d -m755 /usr/share/xml/docbook/xml-dtd-$pkgver
    install -v -d -m755 /etc/xml
    chown -R root:root .
    cp -v -af docbook.cat *.dtd ent/ *.mod \
        /usr/share/xml/docbook/xml-dtd-$pkgver

    if [ ! -e /etc/xml/docbook ]; then
        xmlcatalog --noout --create /etc/xml/docbook
    fi
    xmlcatalog --noout --add "public" \
        "-//OASIS//DTD DocBook XML V$pkgver//EN" \
        "http://www.oasis-open.org/docbook/xml/$pkgver/docbookx.dtd" \
        /etc/xml/docbook
    xmlcatalog --noout --add "public" \
        "-//OASIS//DTD DocBook XML CALS Table Model V$pkgver//EN" \
        "file:///usr/share/xml/docbook/xml-dtd-$pkgver/calstblx.dtd" \
        /etc/xml/docbook
    xmlcatalog --noout --add "public" \
        "-//OASIS//DTD XML Exchange Table Model 19990315//EN" \
        "file:///usr/share/xml/docbook/xml-dtd-$pkgver/soextblx.dtd" \
        /etc/xml/docbook
    xmlcatalog --noout --add "public" \
        "-//OASIS//ELEMENTS DocBook XML Information Pool V$pkgver//EN" \
        "file:///usr/share/xml/docbook/xml-dtd-$pkgver/dbpoolx.mod" \
        /etc/xml/docbook
    xmlcatalog --noout --add "public" \
        "-//OASIS//ELEMENTS DocBook XML Document Hierarchy V$pkgver//EN" \
        "file:///usr/share/xml/docbook/xml-dtd-$pkgver/dbhierx.mod" \
        /etc/xml/docbook
    xmlcatalog --noout --add "public" \
        "-//OASIS//ELEMENTS DocBook XML HTML Tables V$pkgver//EN" \
        "file:///usr/share/xml/docbook/xml-dtd-$pkgver/htmltblx.mod" \
        /etc/xml/docbook
    xmlcatalog --noout --add "public" \
        "-//OASIS//ENTITIES DocBook XML Notations V$pkgver//EN" \
        "file:///usr/share/xml/docbook/xml-dtd-$pkgver/dbnotnx.mod" \
        /etc/xml/docbook
    xmlcatalog --noout --add "public" \
        "-//OASIS//ENTITIES DocBook XML Character Entities V$pkgver//EN" \
        "file:///usr/share/xml/docbook/xml-dtd-$pkgver/dbcentx.mod" \
        /etc/xml/docbook
    xmlcatalog --noout --add "public" \
        "-//OASIS//ENTITIES DocBook XML Additional General Entities V$pkgver//EN" \
        "file:///usr/share/xml/docbook/xml-dtd-$pkgver/dbgenent.mod" \
        /etc/xml/docbook
    xmlcatalog --noout --add "rewriteSystem" \
        "http://www.oasis-open.org/docbook/xml/$pkgver" \
        "file:///usr/share/xml/docbook/xml-dtd-$pkgver" \
        /etc/xml/docbook
    xmlcatalog --noout --add "rewriteURI" \
        "http://www.oasis-open.org/docbook/xml/$pkgver" \
        "file:///usr/share/xml/docbook/xml-dtd-$pkgver" \
        /etc/xml/docbook

    if [ ! -e /etc/xml/catalog ]; then
        xmlcatalog --noout --create /etc/xml/catalog
    fi
    xmlcatalog --noout --add "delegatePublic" \
        "-//OASIS//ENTITIES DocBook XML" \
        "file:///etc/xml/docbook" \
        /etc/xml/catalog
    xmlcatalog --noout --add "delegatePublic" \
        "-//OASIS//DTD DocBook XML" \
        "file:///etc/xml/docbook" \
        /etc/xml/catalog
    xmlcatalog --noout --add "delegateSystem" \
        "http://www.oasis-open.org/docbook/" \
        "file:///etc/xml/docbook" \
        /etc/xml/catalog
    xmlcatalog --noout --add "delegateURI" \
        "http://www.oasis-open.org/docbook/" \
        "file:///etc/xml/docbook" \
        /etc/xml/catalog

    for DTDVERSION in 4.1.2 4.2 4.3 4.4
    do
    xmlcatalog --noout --add "public" \
        "-//OASIS//DTD DocBook XML V$DTDVERSION//EN" \
        "http://www.oasis-open.org/docbook/xml/$DTDVERSION/docbookx.dtd" \
        /etc/xml/docbook
    xmlcatalog --noout --add "rewriteSystem" \
        "http://www.oasis-open.org/docbook/xml/$DTDVERSION" \
        "file:///usr/share/xml/docbook/xml-dtd-$pkgver" \
        /etc/xml/docbook
    xmlcatalog --noout --add "rewriteURI" \
        "http://www.oasis-open.org/docbook/xml/$DTDVERSION" \
        "file:///usr/share/xml/docbook/xml-dtd-$pkgver" \
        /etc/xml/docbook
    xmlcatalog --noout --add "delegateSystem" \
        "http://www.oasis-open.org/docbook/xml/$DTDVERSION/" \
        "file:///etc/xml/docbook" \
        /etc/xml/catalog
    xmlcatalog --noout --add "delegateURI" \
        "http://www.oasis-open.org/docbook/xml/$DTDVERSION/" \
        "file:///etc/xml/docbook" \
        /etc/xml/catalog
    done

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
