#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=docbook-xsl
pkgver=1.79.2

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/$pkgname-nons-$pkgver.tar.* -C $TMP

{ time \
   {

    cd $TMP/$pkgname-nons-$pkgver

    patch -Np1 -i $SRC/$pkgname-nons-$pkgver-stack_fix-1.patch
    
    tar -xf $SRC/docbook-xsl-doc-$pkgver.tar.bz2 --strip-components=1

    install -v -m755 -d /usr/share/xml/docbook/xsl-stylesheets-nons-$pkgver

    cp -v -R VERSION assembly common eclipse epub epub3 extensions fo        \
            highlighting html htmlhelp images javahelp lib manpages params  \
            profiling roundtrip slides template tests tools webhelp website \
            xhtml xhtml-1_1 xhtml5                                          \
        /usr/share/xml/docbook/xsl-stylesheets-nons-$pkgver

    ln -sf VERSION /usr/share/xml/docbook/xsl-stylesheets-nons-$pkgver/VERSION.xsl

    install -v -m644 -D README \
                        /usr/share/doc/docbook-xsl-nons-$pkgver/README.txt
    install -v -m644    RELEASE-NOTES* NEWS* \
                        /usr/share/doc/docbook-xsl-nons-$pkgver

    cp -v -R doc/* /usr/share/doc/docbook-xsl-nons-$pkgver

    if [ ! -d /etc/xml ]; then install -v -m755 -d /etc/xml; fi
    if [ ! -f /etc/xml/catalog ]; then
        xmlcatalog --noout --create /etc/xml/catalog
    fi

    xmlcatalog --noout --add "rewriteSystem" \
            "https://cdn.docbook.org/release/xsl-nons/$pkgver" \
            "/usr/share/xml/docbook/xsl-stylesheets-nons-$pkgver" \
        /etc/xml/catalog

    xmlcatalog --noout --add "rewriteURI" \
            "https://cdn.docbook.org/release/xsl-nons/$pkgver" \
            "/usr/share/xml/docbook/xsl-stylesheets-nons-$pkgver" \
        /etc/xml/catalog

    xmlcatalog --noout --add "rewriteSystem" \
            "https://cdn.docbook.org/release/xsl-nons/current" \
            "/usr/share/xml/docbook/xsl-stylesheets-nons-$pkgver" \
        /etc/xml/catalog

    xmlcatalog --noout --add "rewriteURI" \
            "https://cdn.docbook.org/release/xsl-nons/current" \
            "/usr/share/xml/docbook/xsl-stylesheets-nons-$pkgver" \
        /etc/xml/catalog

    xmlcatalog --noout --add "rewriteSystem" \
            "http://docbook.sourceforge.net/release/xsl/current" \
            "/usr/share/xml/docbook/xsl-stylesheets-nons-$pkgver" \
        /etc/xml/catalog

    xmlcatalog --noout --add "rewriteURI" \
            "http://docbook.sourceforge.net/release/xsl/current" \
            "/usr/share/xml/docbook/xsl-stylesheets-nons-$pkgver" \
        /etc/xml/catalog

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
