#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=efivar
pkgver=37

rm -fr $TMP
mkdir -p $TMP $LOG

#pushd  $SRC
#    git clone https://github.com/rhboot/efivar.git $pkgname-$pkgver
#    tar cf $pkgname-$pkgver.tar.gz $pkgname-$pkgver
#    rm -rf $pkgname-$pkgver
#popd

tar xf $SRC/$pkgname-$pkgver.tar.* -C $TMP

{ time \
   {

   cd $TMP/$pkgname-$pkgver

    make -j1 libdir=/usr/lib

    make libdir=/usr/lib install    

   }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
