#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=exiv2
pkgver=0.27.3

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/$pkgname-$pkgver-Source.tar.gz -C $TMP

{ time \
   {

   cd $TMP/$pkgname-$pkgver-Source

    mkdir build
    cd    build

    cmake -DCMAKE_INSTALL_PREFIX=/usr  \
          -DCMAKE_BUILD_TYPE=Release   \
          -DEXIV2_ENABLE_VIDEO=yes     \
          -DEXIV2_ENABLE_WEBREADY=yes  \
          -DEXIV2_ENABLE_CURL=yes      \
          -DEXIV2_BUILD_SAMPLES=no     \
          -G "Unix Makefiles" ..
    make

    make install

   }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
