#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=ffmpeg
pkgver=4.3.1

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/$pkgname-$pkgver.tar.* -C $TMP

{ time \
   {

    cd $TMP/$pkgname-$pkgver

   sed -i 's/-lflite"/-lflite -lasound"/' configure

   ./configure --prefix=/usr        \
               --enable-gpl         \
               --enable-version3    \
               --enable-nonfree     \
               --disable-static     \
               --enable-shared      \
               --disable-debug      \
               --enable-avresample  \
               --enable-libass      \
               --enable-libfdk-aac  \
               --enable-libfreetype \
               --enable-libmp3lame  \
               --enable-libopus     \
               --enable-libtheora   \
               --enable-libvorbis   \
               --enable-libvpx      \
               --enable-libx264     \
               --enable-libx265     \
               --docdir=/usr/share/doc/$pkgname-$pkgver

   make &&

   gcc tools/qt-faststart.c -o tools/qt-faststart

   make install

   install -v -m755    tools/qt-faststart /usr/bin
   install -v -m755 -d           /usr/share/doc/$pkgname-$pkgver
   install -v -m644    doc/*.txt /usr/share/doc/$pkgname-$pkgver

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
