#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=fftw
pkgver=3.3.8

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/$pkgname-$pkgver.tar.* -C $TMP

{ time \
   {

    cd $TMP/$pkgname-$pkgver

   ./configure --prefix=/usr    \
               --enable-shared  \
               --disable-static \
               --enable-threads \
               --enable-sse2    \
               --enable-avx
   make

   make install

   make clean &&

   ./configure --prefix=/usr    \
               --enable-shared  \
               --disable-static \
               --enable-threads \
               --enable-sse2    \
               --enable-avx     \
               --enable-float
   make

   make install

   make clean

   ./configure --prefix=/usr    \
               --enable-shared  \
               --disable-static \
               --enable-threads \
               --enable-long-double
   make

   make install

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
