#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=fontconfig
pkgver=2.13.1

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/$pkgname-$pkgver.tar.* -C $TMP

{ time \
   {

    cd $TMP/$pkgname-$pkgver

    rm -f src/fcobjshash.h

    ./configure --prefix=/usr        \
                --sysconfdir=/etc    \
                --localstatedir=/var \
                --disable-docs       \
                --docdir=/usr/share/doc/$pkgname-$pkgver
    make

    make install

    install -v -dm755 \
            /usr/share/{man/man{1,3,5},doc/$pkgname-$pkgver/fontconfig-devel}
    install -v -m644 fc-*/*.1         /usr/share/man/man1
    install -v -m644 doc/*.3          /usr/share/man/man3
    install -v -m644 doc/fonts-conf.5 /usr/share/man/man5
    install -v -m644 doc/fontconfig-devel/* \
                                    /usr/share/doc/$pkgname-$pkgver/fontconfig-devel
    install -v -m644 doc/*.{pdf,sgml,txt,html} \
                                    /usr/share/doc/$pkgname-$pkgver

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
