#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=gconf
pkgver=3.2.6

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/Gconf-$pkgver.tar.* -C $TMP

{ time \
   {

    cd $TMP/Gconf-$pkgver

    ./configure --prefix=/usr \
                --sysconfdir=/etc \
                --disable-orbit \
                --disable-static
    make

    make install
    ln -s gconf.xml.defaults /etc/gconf/gconf.xml.system

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
