#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=giflib
pkgver=5.2.1

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/$pkgname-$pkgver.tar.* -C $TMP

{ time \
   {

    cd $TMP/$pkgname-$pkgver

    make

    make PREFIX=/usr install

    find doc \( -name Makefile\* -o -name \*.1 \
            -o -name \*.xml \) -exec rm -v {} \;

    install -v -dm755 /usr/share/doc/$pkgname-$pkgver
    cp -v -R doc/* /usr/share/doc/$pkgname-$pkgver

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
