#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=git
pkgver=2.29.2

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/$pkgname-$pkgver.tar.* -C $TMP

{ time \
   {

   cd $TMP/$pkgname-$pkgver

    ./configure --prefix=/usr \
                --with-gitconfig=/etc/gitconfig \
                --with-python=python3 --with-libpcre2
    make

    make html

    make man

    make perllibdir=/usr/lib/perl5/5.32/site_perl install

    make install-man

    make htmldir=/usr/share/doc/$pkgname-$pkgver install-html

    tar -xf $SRC/git-manpages-$pkgver.tar.xz \
        -C /usr/share/man --no-same-owner --no-overwrite-dir

    mkdir -vp   /usr/share/doc/$pkgname-$pkgver
    tar   -xf   $SRC/git-htmldocs-$pkgver.tar.xz \
          -C    /usr/share/doc/$pkgname-$pkgver --no-same-owner --no-overwrite-dir

    find        /usr/share/doc/$pkgname-$pkgver -type d -exec chmod 755 {} \;
    find        /usr/share/doc/$pkgname-$pkgver -type f -exec chmod 644 {} \;
    
    mkdir -vp /usr/share/doc/$pkgname-$pkgver/man-pages/{html,text}        
    mv        /usr/share/doc/$pkgname-$pkgver/{git*.txt,man-pages/text}    
    mv        /usr/share/doc/$pkgname-$pkgver/{git*.,index.,man-pages/}html

    mkdir -vp /usr/share/doc/$pkgname-$pkgver/technical/{html,text}        
    mv        /usr/share/doc/$pkgname-$pkgver/technical/{*.txt,text}       
    mv        /usr/share/doc/$pkgname-$pkgver/technical/{*.,}html          

    mkdir -vp /usr/share/doc/$pkgname-$pkgver/howto/{html,text}            
    mv        /usr/share/doc/$pkgname-$pkgver/howto/{*.txt,text}           
    mv        /usr/share/doc/$pkgname-$pkgver/howto/{*.,}html              

    sed -i '/^<a href=/s|howto/|&html/|' /usr/share/doc/$pkgname-$pkgver/howto-index.html
    sed -i '/^\* link:/s|howto/|&html/|' /usr/share/doc/$pkgname-$pkgver/howto-index.txt    

   }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
