#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=glib
pkgver=2.66.3

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/$pkgname-$pkgver.tar.* -C $TMP

{ time \
   {

    cd $TMP/$pkgname-$pkgver

      patch -Np1 -i $SRC/$pkgname-$pkgver-skip_warnings-1.patch

      mkdir build 
      cd    build 

      meson --prefix=/usr      \
            -Dman=true         \
            -Dselinux=disabled -Dgtk_doc=true \
            ..                 
      ninja

      ninja install 

      mkdir -p /usr/share/doc/$pkgname-$pkgver 
      cp -r ../docs/reference/{NEWS,gio,glib,gobject} /usr/share/doc/$pkgname-$pkgver

      rm -f /usr/include/glib-2.0/glib/gurifuncs.h

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
