#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=gpm
pkgver=1.20.7

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/$pkgname-$pkgver.tar.* -C $TMP

{ time \
   {

    cd $TMP/$pkgname-$pkgver

    patch -Np1 -i $SRC/$pkgname-$pkgver-consolidated-1.patch 
    ./autogen.sh                                     
    ./configure --prefix=/usr --sysconfdir=/etc      
    make

    make install                                          

    install-info --dir-file=/usr/share/info/dir           \
                 /usr/share/info/gpm.info                 

    ln -sfv libgpm.so.2.1.0 /usr/lib/libgpm.so            
    install -v -m644 conf/gpm-root.conf /etc              

    install -v -m755 -d /usr/share/doc/$pkgname-$pkgver/support 
    install -v -m644    doc/support/*                     \
                        /usr/share/doc/$pkgname-$pkgver/support 
    install -v -m644    doc/{FAQ,HACK_GPM,README*}        \
                        /usr/share/doc/$pkgname-$pkgver

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
