#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=graphite2
pkgver=1.3.14

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/$pkgname-$pkgver.tar.* -C $TMP

{ time \
   {

    cd $TMP/$pkgname-$pkgver

    sed -i '/cmptest/d' tests/CMakeLists.txt

    mkdir build
    cd    build

    cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_VERBOSE_MAKEFILE=ON ..
    make

    make docs

    make install

    install -v -d -m755 /usr/share/doc/$pkgname-$pkgver

    cp      -v -f    doc/{GTF,manual}.html \
                        /usr/share/doc/$pkgname-$pkgver
    cp      -v -f    doc/{GTF,manual}.pdf \
                        /usr/share/doc/$pkgname-$pkgver

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
