#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=grub-efi
pkgver=2.04

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/grub-$pkgver.tar.* -C $TMP

{ time \
   {

   cd $TMP/grub-$pkgver

    ./configure --prefix=/usr            \
        --sbindir=/sbin                  \
        --sysconfdir=/etc                \
        --disable-efiemu                 \
        --enable-grub-mkfont             \
        --with-platform=efi              \
        --enable-boot-time               \
        --enable-device-mapper           \
        --target=x86_64                  \
        --enable-cache-stats             \
        --enable-mm-debug                \
        --enable-nls                     \
        --prefix="/usr"                  \
        --bindir="/usr/bin"              \
        --mandir="/usr/share/man"        \
        --infodir="/usr/share/info"      \
        --datarootdir="/usr/share"       \
        --program-prefix=""              \
        --with-bootdir="/boot"           \
        --with-grubdir="grub"            \
        --disable-silent-rules           \
        --disable-werror
    make
    make  install 

   }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
