#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=gtk2
pkgver=2.24.32

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/gtk+-2.24.32.tar.xz -C $TMP

{ time \
   {

    cd $TMP/gtk+-2.24.32

    sed -e 's#l \(gtk-.*\).sgml#& -o \1#' \
        -i docs/{faq,tutorial}/Makefile.in

    ./configure --prefix=/usr --sysconfdir=/etc --enable-gtk-doc

    make

    make install

    cat > ~/.gtkrc-2.0 << "EOF"
include "/usr/share/themes/Glider/gtk-2.0/gtkrc"
gtk-icon-theme-name = "hicolor"
EOF

    cat > /etc/gtk-2.0/gtkrc << "EOF"
include "/usr/share/themes/Clearlooks/gtk-2.0/gtkrc"
gtk-icon-theme-name = "elementary"
EOF

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
