#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=js78
pkgver=78.5.0

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/firefox-78.5.0esr.source.tar.xz -C $TMP

{ time \
   {

    cd $TMP/firefox-78.5.0

    mountpoint -q /dev/shm || mount -t tmpfs devshm /dev/shm
    
    export SHELL=/bin/bash

    mkdir obj
    cd    obj

    CC=gcc CXX=g++ \
    ../js/src/configure --prefix=/usr            \
                        --with-intl-api          \
                        --with-system-zlib       \
                        --with-system-icu        \
                        --disable-jemalloc       \
                        --disable-debug-symbols  \
                        --enable-readline       
    make

    make install
    rm -v /usr/lib/libjs_static.ajs
    sed -i '/@NSPR_CFLAGS@/d' /usr/bin/js78-config

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
