#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=krb5
pkgver=1.18.3

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/$pkgname-$pkgver.tar.* -C $TMP

{ time \
   {

    cd $TMP/$pkgname-$pkgver

    cd src
     
    sed -i -e 's@\^u}@^u cols 300}@' tests/dejagnu/config/default.exp    
    sed -i -e '/eq 0/{N;s/12 //}'    plugins/kdb/db2/libdb2/test/run.test

    ./configure --prefix=/usr            \
                --sysconfdir=/etc        \
                --localstatedir=/var/lib \
                --with-system-et         \
                --with-system-ss         \
                --with-system-verto=no   \
                --enable-dns-for-realm
    make

    make install

    for f in gssapi_krb5 gssrpc k5crypto kadm5clnt kadm5srv \
             kdb5 kdb_ldap krad krb5 krb5support verto ; do

        find /usr/lib -type f -name "lib$f*.so*" -exec chmod -v 755 {} \;    
    done         

    mv -v /usr/lib/libkrb5.so.3*        /lib
    mv -v /usr/lib/libk5crypto.so.3*    /lib
    mv -v /usr/lib/libkrb5support.so.0* /lib

    ln -v -sf ../../lib/libkrb5.so.3.3        /usr/lib/libkrb5.so       
    ln -v -sf ../../lib/libk5crypto.so.3.1    /usr/lib/libk5crypto.so   
    ln -v -sf ../../lib/libkrb5support.so.0.1 /usr/lib/libkrb5support.so

    mv -v /usr/bin/ksu /bin
    chmod -v 755 /bin/ksu  

    install -v -dm755 /usr/share/doc/$pkgname-$pkgver
    cp -vfr ../doc/*  /usr/share/doc/$pkgname-$pkgver

    cat > /etc/krb5.conf << "EOF"
# Begin /etc/krb5.conf

[libdefaults]
        default_realm = ATHENA.MIT.EDU

[realms]
# use "kdc = ..." if realm admins haven't put SRV records into DNS
        ATHENA.MIT.EDU = {
                admin_server = kerberos.mit.edu
        }
        ANDREW.CMU.EDU = {
                admin_server = kdc-01.andrew.cmu.edu
        }

[domain_realm]
        mit.edu = ATHENA.MIT.EDU
        csail.mit.edu = CSAIL.MIT.EDU
        .ucsc.edu = CATS.UCSC.EDU

[logging]
#       kdc = CONSOLE

# End /etc/krb5.conf
EOF

    tar xf $SRC/blfs-systemd-units-20200828.tar.xz
    cd blfs-systemd-units-20200828
    make install-krb5

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
