#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=libassuan
pkgver=2.5.4

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/$pkgname-$pkgver.tar.* -C $TMP

{ time \
   {

    cd $TMP/$pkgname-$pkgver

    ./configure --prefix=/usr
    make

    make -C doc html
    makeinfo --html --no-split -o doc/assuan_nochunks.html doc/assuan.texi
    makeinfo --plaintext       -o doc/assuan.txt           doc/assuan.texi

    make install &&

    install -v -dm755   /usr/share/doc/$pkgname-$pkgver/html
    install -v -m644 doc/assuan.html/* \
                        /usr/share/doc/$pkgname-$pkgver/html
    install -v -m644 doc/assuan_nochunks.html \
                        /usr/share/doc/$pkgname-$pkgver
    install -v -m644 doc/assuan.{txt,texi} \
                        /usr/share/doc/$pkgname-$pkgver

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
