#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=liba52
pkgver=0.7.4

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/a52dec-$pkgver.tar.* -C $TMP

{ time \
   {

   cd $TMP/a52dec-$pkgver

    ./configure --prefix=/usr \
                --mandir=/usr/share/man \
                --enable-shared \
                --disable-static \
                CFLAGS="-g -O2 $([ $(uname -m) = x86_64 ] echo -fPIC)"
    make

    make install
    cp liba52/a52_internal.h /usr/include/a52dec
    install -v -m644 -D doc/liba52.txt \
        /usr/share/doc/liba52-$pkgver/liba52.txt

   }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
