#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=libcap-pam
pkgver=2.45

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/libcap-$pkgver.tar.* -C $TMP

{ time \
   {

    cd $TMP/libcap-$pkgver

    make -C pam_cap

    install -v -m755 pam_cap/pam_cap.so /lib/security
    install -v -m644 pam_cap/capability.conf /etc/security

    mv -v /etc/pam.d/system-auth{,.bak}
    cat > /etc/pam.d/system-auth << "EOF"
# Begin /etc/pam.d/system-auth

auth      optional    pam_cap.so
EOF
    tail -n +3 /etc/pam.d/system-auth.bak >> /etc/pam.d/system-auth

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
