#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=libgcrypt
pkgver=1.8.7

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/$pkgname-$pkgver.tar.* -C $TMP

{ time \
   {

    cd $TMP/$pkgname-$pkgver

    ./configure --prefix=/usr --with-capabilities
    make                     

    make -C doc html                                                      
    makeinfo --html --no-split -o doc/gcrypt_nochunks.html doc/gcrypt.texi
    makeinfo --plaintext       -o doc/gcrypt.txt           doc/gcrypt.texi

    make install
    install -v -dm755   /usr/share/doc/$pkgname-$pkgver
    install -v -m644    README doc/{README.apichanges,fips*,libgcrypt*} \
                        /usr/share/doc/$pkgname-$pkgver

    install -v -dm755   /usr/share/doc/$pkgname-$pkgver/html
    install -v -m644 doc/gcrypt.html/* \
                        /usr/share/doc/$pkgname-$pkgver/html
    install -v -m644 doc/gcrypt_nochunks.html \
                        /usr/share/doc/$pkgname-$pkgver     
    install -v -m644 doc/gcrypt.{txt,texi} \
                        /usr/share/doc/$pkgname-$pkgver

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
