#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=libical
pkgver=3.0.8

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/$pkgname-$pkgver.tar.* -C $TMP

{ time \
   {

    cd $TMP/$pkgname-$pkgver

    sed -i '/define LEAP_MONTH/a #define FALSE 0' src/libical/icalrecur.c
    sed -i 's/array/arraytest/'       src/test/libical-glib/CMakeLists.txt
    mv src/test/libical-glib/array.py src/test/libical-glib/arraytest.py

    mkdir build
    cd    build

    cmake -DCMAKE_INSTALL_PREFIX=/usr  \
          -DCMAKE_BUILD_TYPE=Release   \
          -DSHARED_ONLY=yes            \
          -DICAL_BUILD_DOCS=false      \
          -DGOBJECT_INTROSPECTION=true \
          -DICAL_GLIB_VAPI=true        \
          -DUSE_BUILTIN_TZDATA=yes     \
          ..
    make

    make install

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
