#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=libnl
pkgver=3.5.0

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/$pkgname-$pkgver.tar.* -C $TMP

{ time \
   {

    cd $TMP/$pkgname-$pkgver

    ./configure --prefix=/usr     \
                --sysconfdir=/etc \
                --disable-static
    make

    make install

    mkdir -vp /usr/share/doc/$pkgname-$pkgver
    tar -xf $SRC/libnl-doc-$pkgver.tar.gz --strip-components=1 --no-same-owner \
        -C  /usr/share/doc/$pkgname-$pkgver

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
