#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=libpng
pkgver=1.6.37

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/$pkgname-$pkgver.tar.* -C $TMP

{ time \
   {

    cd $TMP/$pkgname-$pkgver

    gzip -cd $SRC/$pkgname-$pkgver-apng.patch.gz | patch -p1

    ./configure --prefix=/usr --disable-static
    make

    make install
    mkdir -v /usr/share/doc/$pkgname-$pkgver
    cp -v README libpng-manual.txt /usr/share/doc/$pkgname-$pkgver

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
