#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=libraw
pkgver=0.20.2

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/LibRaw-$pkgver.tar.* -C $TMP

{ time \
   {

   cd $TMP/LibRaw-$pkgver

    autoreconf -fiv             
    ./configure --prefix=/usr    \
                --enable-jpeg    \
                --enable-jasper  \
                --enable-lcms    \
                --disable-static \
                --docdir=/usr/share/doc/$pkgname-$pkgver
    make

    make install

   }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
