#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=libsoup
pkgver=2.72.0

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/$pkgname-$pkgver.tar.* -C $TMP

{ time \
   {

   cd $TMP/$pkgname-$pkgver

    patch -Np1 -i $SRC/$pkgname-$pkgver-testsuite_fix-1.patch

    mkdir build
    cd    build

    meson --prefix=/usr -Dvapi=enabled -Dgssapi=disabled -Ddoc=enabled ..
    ninja

    ninja install

   }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
