#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=libtheora
pkgver=1.1.1

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/$pkgname-$pkgver.tar.* -C $TMP

{ time \
   {

    cd $TMP/$pkgname-$pkgver

    sed -i 's/png_\(sizeof\)/\1/g' examples/png2theora.c
    ./configure --prefix=/usr --disable-static
    make

    make install

    cd examples/.libs
    for E in *; do
      install -v -m755 $E /usr/bin/theora_${E}
    done

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
