#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=libtiff
pkgver=4.1.0

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/$pkgname-$pkgver.tar.* -C $TMP

{ time \
   {

    cd $TMP/$pkgname-$pkgver

    mkdir -p libtiff-build
    cd       libtiff-build

    cmake -DCMAKE_INSTALL_DOCDIR=/usr/share/doc/$pkgname-$pkgver \
          -DCMAKE_INSTALL_PREFIX=/usr -G Ninja ..
    ninja

    ninja install

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
