#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=libxau
pkgver=1.0.9

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/libXau-$pkgver.tar.* -C $TMP

{ time \
   {

    cd $TMP/libXau-$pkgver

    export XORG_PREFIX=/usr
    export XORG_CONFIG="--prefix=$XORG_PREFIX --sysconfdir=/etc \
        --localstatedir=/var --disable-static"

    ./configure $XORG_CONFIG
    make

    make install

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
