#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=libxcb
pkgver=1.14

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/$pkgname-$pkgver.tar.* -C $TMP

{ time \
   {

    cd $TMP/$pkgname-$pkgver

    export XORG_PREFIX=/usr
    export XORG_CONFIG="--prefix=$XORG_PREFIX --sysconfdir=/etc \
        --localstatedir=/var --disable-static"

    CFLAGS=-Wno-error=format-extra-args ./configure $XORG_CONFIG      \
                --without-doxygen \
                --docdir='${datadir}'/doc/$pkgname-$pkgver
    make

    make install

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
