#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=libxslt
pkgver=1.1.34

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/$pkgname-$pkgver.tar.* -C $TMP

{ time \
   {

    cd $TMP/$pkgname-$pkgver

    sed -i s/3000/5000/ libxslt/transform.c doc/xsltproc.{1,xml}
    ./configure --prefix=/usr --disable-static --without-python
    make

    sed -e 's@http://cdn.docbook.org/release/xsl@https://cdn.docbook.org/release/xsl-nons@' \
        -e 's@\$Date\$@31 October 2019@' -i doc/xsltproc.xml
    xsltproc/xsltproc --nonet doc/xsltproc.xml -o doc/xsltproc.1

    make install

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
