#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=libxml2
pkgver=2.9.10

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/$pkgname-$pkgver.tar.* -C $TMP

{ time \
   {

    cd $TMP/$pkgname-$pkgver

    patch -p1 -i $SRC/$pkgname-$pkgver-security_fixes-1.patch

    sed -i '/if Py/{s/Py/(Py/;s/)/))/}' python/{types.c,libxml.c}

    sed -i 's/test.test/#&/' python/tests/tstLastError.py

    sed -i 's/ TRUE/ true/' encoding.c

    ./configure --prefix=/usr    \
                --disable-static \
                --with-history   \
                --with-python=/usr/bin/python3  --with-icu  --with-threads
    make

    tar xf $SRC/xmlts20130923.tar.gz

    make install

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
