#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=links
pkgver=2.21

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/$pkgname-$pkgver.tar.* -C $TMP

{ time \
   {

    cd $TMP/$pkgname-$pkgver

    ./configure --prefix=/usr --mandir=/usr/share/man --enable-graphics
    make

    make install
    install -v -d -m755 /usr/share/doc/$pkgname-$pkgver
    install -v -m644 doc/links_cal/* KEYS BRAILLE_HOWTO \
        /usr/share/doc/$pkgname-$pkgver

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
