#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=lm-sensors
pkgver=3-6-0

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/$pkgname-$pkgver.tar.* -C $TMP

{ time \
   {

    cd $TMP/$pkgname-$pkgver

    make PREFIX=/usr        \
         BUILD_STATIC_LIB=0 \
         MANDIR=/usr/share/man

    make PREFIX=/usr        \
         BUILD_STATIC_LIB=0 \
         MANDIR=/usr/share/man install

    install -v -m755 -d /usr/share/doc/lm_sensors-$pkgver
    cp -rv              README INSTALL doc/* \
                        /usr/share/doc/lm_sensors-$pkgver

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
