#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=lmdb
pkgver=0.9.24

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/lmdb-LMDB_$pkgver.tar.* -C $TMP

{ time \
   {

    cd $TMP/lmdb-LMDB_$pkgver

    cd libraries/liblmdb
    make                
    sed -i 's| liblmdb.a||' Makefile

    make prefix=/usr install

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
