#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=lsb-release
pkgver=1.4

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/$pkgname-$pkgver.tar.* -C $TMP

{ time \
   {

   cd $TMP/$pkgname-$pkgver

   make

   make install

   cat > /etc/lsb-release << "EOF"
LSB_VERSION=1.0
DISTRIB_ID=Beginnings
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Beginnings Linux"
EOF

   }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
