#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=lvm2
pkgver=2.03.10

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/LVM2.$pkgver.tgz -C $TMP

{ time \
   {

    cd $TMP/LVM2.$pkgver

    SAVEPATH=$PATH                 
    PATH=$PATH:/sbin:/usr/sbin     
    ./configure --prefix=/usr       \
                --exec-prefix=      \
                --enable-cmdlib     \
                --enable-pkgconfig  \
                --enable-udev_sync  --with-cache=internal --with-thin=internal
    make                           
    PATH=$SAVEPATH                 
    unset SAVEPATH

    make install
    make install_systemd_units

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
