#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=lynx
pkgver=2.8.9rel.1

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/$pkgname$pkgver.tar.* -C $TMP

{ time \
   {

    cd $TMP/$pkgname$pkgver

    ./configure --prefix=/usr          \
                --sysconfdir=/etc/lynx \
                --datadir=/usr/share/doc/$pkgname-$pkgver \
                --with-zlib            \
                --with-bzlib           \
                --with-ssl             \
                --with-screen=ncursesw \
                --enable-locale-charset
    make

    make install-full
    chgrp -v -R root /usr/share/doc/$pkgname-$pkgver/lynx_doc

    sed -e '/#LOCALE/     a LOCALE_CHARSET:TRUE'     \
        -i /etc/lynx/lynx.cfg

    sed -e '/#DEFAULT_ED/ a DEFAULT_EDITOR:vi'       \
        -i /etc/lynx/lynx.cfg
        
    sed -e '/#PERSIST/    a PERSISTENT_COOKIES:TRUE' \
        -i /etc/lynx/lynx.cfg        

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
