#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=mlt
pkgver=6.22.1

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/$pkgname-$pkgver.tar.* -C $TMP

{ time \
   {

   cd $TMP/$pkgname-$pkgver
    
    sed -i 's|-D__LINUX_PULSE__||' src/modules/rtaudio/Makefile

    ./configure --prefix=/usr     \
                --enable-gpl      \
                --enable-gpl3     \
                --enable-opengl   \
                --disable-gtk2
    make

    make install

   }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
