#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=modemmanager
pkgver=1.14.8

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/ModemManager-$pkgver.tar.* -C $TMP

{ time \
   {

    cd $TMP/ModemManager-$pkgver

    ./configure --prefix=/usr                 \
                --sysconfdir=/etc             \
                --localstatedir=/var          \
                --with-systemd-journal        \
                --with-systemd-suspend-resume \
                --disable-static --enable-gtk-doc
    make

    make install

    systemctl enable ModemManager

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
