#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=nasm
pkgver=2.15.05

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/$pkgname-$pkgver.tar.* -C $TMP

{ time \
   {

    cd $TMP/$pkgname-$pkgver

    tar -xf $SRC/$pkgname-$pkgver-xdoc.tar.xz --strip-components=1

    ./configure --prefix=/usr
    make

    make install

    install -m755 -d         /usr/share/doc/$pkgname-$pkgver/html
    cp -v doc/html/*.html    /usr/share/doc/$pkgname-$pkgver/html
    cp -v doc/*.{txt,ps,pdf} /usr/share/doc/$pkgname-$pkgver

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
