#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=networkmanager
pkgver=1.26.4

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/NetworkManager-$pkgver.tar.* -C $TMP

{ time \
   {

   cd $TMP/NetworkManager-$pkgver

    sed -e 's/-qt4/-qt5/'              \
        -e 's/moc_location/host_bins/' \
        -i examples/C/qt/meson.build

    sed -e 's/Qt/&5/'                  \
        -i meson.build

    sed '/initrd/d' -i src/meson.build

    grep -rl '^#!.*python$' | xargs sed -i '1s/python/&3/'

    mkdir build
    cd    build

    CXXFLAGS+="-O2 -fPIC"            \
    meson --prefix /usr              \
          -Djson_validation=false    \
          -Dlibaudit=no              \
          -Dlibpsl=false             \
          -Dnmtui=true               \
          -Dovs=false                \
          -Dppp=false                \
          -Dselinux=false            \
          -Dqt=false                 \
          -Dudev_dir=/lib/udev       \
          -Dsession_tracking=systemd \
          -Dmodem_manager=false      \
          -Dsystemdsystemunitdir=/lib/systemd/system \
          .. &&
    ninja

    ninja install &&
    mv -v /usr/share/doc/NetworkManager{,-1.26.4}

    cat >> /etc/NetworkManager/NetworkManager.conf << "EOF"
[main]
plugins=keyfile
EOF

    systemctl enable NetworkManager
    systemctl disable NetworkManager-wait-online

   }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
