#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=newt
pkgver=0.52.21

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/$pkgname-$pkgver.tar.* -C $TMP

{ time \
   {

    cd $TMP/$pkgname-$pkgver

    sed -e 's/^LIBNEWT =/#&/' \
        -e '/install -m 644 $(LIBNEWT)/ s/^/#/' \
        -e 's/$(LIBNEWT)/$(LIBNEWTSONAME)/g' \
        -i Makefile.in 

    ./configure --prefix=/usr --with-gpm-support
    make

    make install

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
