#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=noto-fonts
pkgver=1.4

rm -fr $TMP
mkdir -p $TMP $LOG

{ time \
   {

    mkdir -pv /usr/share/fonts/truetype/noto-fonts
    mkdir -pv noto-fonts && cd noto-fonts

    find ./$SRC/ -name "Noto*-hinted.zip" -exec sudo unzip -o {} -d /usr/share/fonts/truetype/noto-fonts \;
    find ./$SRC/ -name "Noto*-unhinted.zip" -exec sudo unzip -o {} -d /usr/share/fonts/truetype/noto-fonts \;

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
