#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=p11-kit
pkgver=3.59

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/$pkgname-$pkgver.tar.* -C $TMP

{ time \
   {

    cd $TMP/$pkgname-$pkgver

    patch -Np1 -i $SRC/$pkgname-$pkgver-standalone-1.patch

    cd nss

    make BUILD_OPT=1                        \
        NSPR_INCLUDE_DIR=/usr/include/nspr  \
        USE_SYSTEM_ZLIB=1                   \
        ZLIB_LIBS=-lz                       \
        NSS_ENABLE_WERROR=0                 \
        $([ $(uname -m) = x86_64 ] && echo USE_64=1) \
        $([ -f /usr/include/sqlite3.h ] && echo NSS_USE_SYSTEM_SQLITE=1)

    cd ../dist

    install -v -m755 Linux*/lib/*.so              /usr/lib
    install -v -m644 Linux*/lib/{*.chk,libcrmf.a} /usr/lib        

    install -v -m755 -d                           /usr/include/nss
    cp -v -RL {public,private}/nss/*              /usr/include/nss
    chmod -v 644                                  /usr/include/nss/*

    install -v -m755 Linux*/bin/{certutil,nss-config,pk12util} /usr/bin

    install -v -m644 Linux*/lib/pkgconfig/nss.pc  /usr/lib/pkgconfig

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
