#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=ntfs-3g
pkgver=2017.3.23

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/ntfs-3g_ntfsprogs-2017.3.23.tgz -C $TMP

{ time \
   {

    cd $TMP/ntfs-3g_ntfsprogs-2017.3.23

    ./configure --prefix=/usr        \
                --disable-static     \
                --with-fuse=internal \
                --docdir=/usr/share/doc/$pkgname-$pkgver
    make

    make install
    ln -sv ../bin/ntfs-3g /sbin/mount.ntfs
    ln -sv ntfs-3g.8 /usr/share/man/man8/mount.ntfs.8

    chmod -v 4755 /bin/ntfs-3g

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
