#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=oxygen-fonts
pkgver=5.4.3

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/oxygen-fonts-5.4.3-x86_64.tar.xz -C $TMP

{ time \
   {

    cd $TMP/oxygen-fonts-5.4.3-x86_64

    cp -rv share /usr/
    cp -r lib64/* /usr/lib/

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
