#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=p7zip
pkgver=16.02

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/${pkgname}_${pkgver}_src_all.tar.* -C $TMP

{ time \
   {

   cd $TMP/${pkgname}_${pkgver}

    patch -Np1 -i $SRC/$pkgname-$pkgver-consolidated_fixes-1.patch

    make all3

    make DEST_HOME=/usr \
         DEST_MAN=/usr/share/man \
         DEST_SHARE_DOC=/usr/share/doc/$pkgname-$pkgver install

   }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
