#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=parted
pkgver=3.3

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/$pkgname-$pkgver.tar.* -C $TMP

{ time \
   {

    cd $TMP/$pkgname-$pkgver

    ./configure --prefix=/usr --disable-static
    make

    make -C doc html                                      
    makeinfo --html      -o doc/html       doc/parted.texi
    makeinfo --plaintext -o doc/parted.txt doc/parted.texi

    make install
    install -v -m755 -d /usr/share/doc/$pkgname-$pkgver/html
    install -v -m644    doc/html/* \
                        /usr/share/doc/$pkgname-$pkgver/html
    install -v -m644    doc/{FAT,API,parted.{txt,html}} \
                        /usr/share/doc/$pkgname-$pkgver

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
