#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=pcre
pkgver=8.44

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/$pkgname-$pkgver.tar.* -C $TMP

{ time \
   {

    cd $TMP/$pkgname-$pkgver

    ./configure --prefix=/usr                     \
                --docdir=/usr/share/doc/$pkgname-$pkgver \
                --enable-unicode-properties       \
                --enable-pcre16                   \
                --enable-pcre32                   \
                --enable-pcregrep-libz            \
                --enable-pcregrep-libbz2          \
                --enable-pcretest-libreadline     \
                --disable-static   --with-pcre=system 
    make

    make install
    mv -v /usr/lib/libpcre.so.* /lib
    ln -sfv ../../lib/$(readlink /usr/lib/libpcre.so) /usr/lib/libpcre.so

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
