#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=perl-test-needs
pkgver=0.002006

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/Test-Needs-0.002006.tar.gz -C $TMP

{ time \
   {

    cd $TMP/Test-Needs-0.002006

    perl Makefile.PL
    make            
    make test

    make install

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
