#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=perl-uri
pkgver=5.05

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/URI-$pkgver.tar.gz -C $TMP

{ time \
   {

    cd $TMP/URI-$pkgver

    perl Makefile.PL
    make            
    make test

    make install

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
