#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=plasma-frameworks
pkgver=5.73

rm -fr $TMP
mkdir -p $TMP $LOG

{ time \
   {

    mkdir -pv $SRC/$pkgname-$pkgver
    cd $SRC/$pkgname-$pkgver

    url=http://download.kde.org/stable/frameworks/$pkgver/
    wget -r -nH -nd -A '*.xz' -np $url

    cat > frameworks-$pkgver.md5 << "EOF"
c33040192815708c5f075b1dbd01a2be  attica-$pkgver.tar.xz
#3a3b7489583b9b412ff18316b7ab2912  extra-cmake-modules-$pkgver.tar.xz
342ec19fd7e65cafd3d58220f144ebc8  kapidox-$pkgver.tar.xz
33de1f53ec53e7112396ded8c3306d02  karchive-$pkgver.tar.xz
03107a85b830b212e268f51cf2cbe668  kcodecs-$pkgver.tar.xz
c1d584f109de507e91a357585bccd445  kconfig-$pkgver.tar.xz
f3e0b26a1b63fee56fb74b1bf972aac2  kcoreaddons-$pkgver.tar.xz
f6668c75a63f2b62997bde8c644244d0  kdbusaddons-$pkgver.tar.xz
756b06b64a324d9c930b560a6d082d06  kdnssd-$pkgver.tar.xz
7d68d806497104cd7febecdeb72b01f6  kguiaddons-$pkgver.tar.xz
b62f7fc855504f2372ee6c79a6bc40d7  ki18n-$pkgver.tar.xz
888748e6c1e7c706ab0620dd06881821  kidletime-$pkgver.tar.xz
fc9c81792d222bd82012ffea28508b09  kimageformats-$pkgver.tar.xz
c83f878fd79b5b2d03f89395d2e14986  kitemmodels-$pkgver.tar.xz
913b467848b103df05bbf95ea37ba9ec  kitemviews-$pkgver.tar.xz
34fef335c2070bfa0ac7bf468add65f6  kplotting-$pkgver.tar.xz
26d211cae109afaa5bc0510e857fdf28  kwidgetsaddons-$pkgver.tar.xz
80674f9e664040a9f25e2a762473fc0f  kwindowsystem-$pkgver.tar.xz
74bc1a1d23993391a481f3a4a1c016a1  networkmanager-qt-$pkgver.tar.xz
6121d847448048fe92b12264e82d8c9e  solid-$pkgver.tar.xz
05a961ee1ed39e1f4d98aab99c02930e  sonnet-$pkgver.tar.xz
927e8df5d6440cab69614a825e111c2d  threadweaver-$pkgver.tar.xz
aa1e7532c695d9e8b6a213fa725bae1e  kauth-$pkgver.tar.xz
7e5263945014cc97726ec1fd855bd331  kcompletion-$pkgver.tar.xz
40d87aa27174706e6df0b2807b114b56  kcrash-$pkgver.tar.xz
c7e7b638940c5f6abae59c1195ec37fe  kdoctools-$pkgver.tar.xz
ba450e3e2edf7679b140b64f1938feb2  kpty-$pkgver.tar.xz
2df82e84a1f22dc72121490e3c325de0  kunitconversion-$pkgver.tar.xz
f4f7c5f17f829e7df2395ab1dbd7243d  kconfigwidgets-$pkgver.tar.xz
22ad03ccdb3243e850ca30d16c6771f1  kservice-$pkgver.tar.xz
cf047279f13f72cd78784067fd1d6518  kglobalaccel-$pkgver.tar.xz
f39a62f40255dbe54295c72779bdbad3  kpackage-$pkgver.tar.xz
0042487aad83241f52c1116cc67fe470  kdesu-$pkgver.tar.xz
79781c58d3a8433ff8de5d5e1031cd7a  kemoticons-$pkgver.tar.xz
23d7226b57acbf5be919b3848592c624  kiconthemes-$pkgver.tar.xz
3a2282e410983f1847463cb7a4d8985e  kjobwidgets-$pkgver.tar.xz
b5b5b3b1482a880ca714ceac28624646  knotifications-$pkgver.tar.xz
508bdf33c3fb27bfb577d01599a69f39  ktextwidgets-$pkgver.tar.xz
1591c913577d800f03d079545c8d5411  kxmlgui-$pkgver.tar.xz
083059e5b6f2285d1e803de121d797da  kbookmarks-$pkgver.tar.xz
905c9d5f68ab24af1378b6373ff2136b  kwallet-$pkgver.tar.xz
3b51763b90c604f46b7be40e8e620d42  kded-$pkgver.tar.xz
9662956fa936f5784e72c56d3b92df84  kio-$pkgver.tar.xz
b7342c3e6d5d121a062a4fec0b12b440  kdeclarative-$pkgver.tar.xz
d5416a83f5fb657191943f78c3f53132  kcmutils-$pkgver.tar.xz
e48190fb43e340f4d8af0af761313ff5  kirigami2-$pkgver.tar.xz
3031ba0db06c655902c48149ebb0aa47  knewstuff-$pkgver.tar.xz
628f3ba2f966ea5853d7db7e89c1aa25  frameworkintegration-$pkgver.tar.xz
62352e83bcc895af5668ed350dfe6c9d  kinit-$pkgver.tar.xz
78ed1d6c89cfc50837b339fef0d1aa42  knotifyconfig-$pkgver.tar.xz
baea3312a026f6e7d0754b1d3c87d52c  kparts-$pkgver.tar.xz
83d12c191cb16343603710dd12549de9  kactivities-$pkgver.tar.xz
#7f77d7f55abc4ea9db3dd786b514ee58  kdewebkit-$pkgver.tar.xz
171ec7fbb842a65bc8c0ef8832bc1b0a  syntax-highlighting-$pkgver.tar.xz
0daa36a7e0440715bb9d028e3a6a79dd  ktexteditor-$pkgver.tar.xz
da21560291ac5ca797807017b690526c  kdesignerplugin-$pkgver.tar.xz
cce15d3618ccf85d66dd3ce00ef119bf  kwayland-$pkgver.tar.xz
3fb4c9624ccf587b9692b9f18bf8e78e  plasma-framework-$pkgver.tar.xz
#f05b39b8de0e8f17acdc52d266b39f95  modemmanager-qt-$pkgver.tar.xz
87528365a0f41fa9f65a8314b2b30b64  kpeople-$pkgver.tar.xz
b279ad2c0c188540f88b5291cccd12f4  kxmlrpcclient-$pkgver.tar.xz
81e1638b9915ef293a5fcb651679b025  bluez-qt-$pkgver.tar.xz
bf2731aca806de7d9e1f57eb164dccce  kfilemetadata-$pkgver.tar.xz
0ccd995814833ffeba852db8469d8ecd  baloo-$pkgver.tar.xz
#335cc472ede625d4c986601fa46a0de7  breeze-icons-$pkgver.tar.xz
#1a1b69517c3e5054e8c3fc5a863424d2  oxygen-icons5-$pkgver.tar.xz
527bb4e18d0c934c4ceb6bb888e27be6  kactivities-stats-$pkgver.tar.xz
b2c41005086aa5923396b76a97654b4e  krunner-$pkgver.tar.xz
#c5777bd5809f74a5595ab6b9d58c088c  prison-$pkgver.tar.xz
83485bd9da3a945de012707b1ee11f03  qqc2-desktop-style-$pkgver.tar.xz
2f25ea46a7ae7ff942a3b12457710bc9  kjs-$pkgver.tar.xz
7daadf02818f6e58853e151f5a246524  kdelibs4support-$pkgver.tar.xz
c79f45f59e5ddc53359d008dc1266c63  khtml-$pkgver.tar.xz
e4bc354a2908888098e9ca17a5888bc9  kjsembed-$pkgver.tar.xz
7652778ab2e57bb49d930450650c86da  kmediaplayer-$pkgver.tar.xz
9255465cc898c9e9e1afcc6876a725fd  kross-$pkgver.tar.xz
ca82fa202e9b6d7ebcf6c4f5c4bdfbe5  kholidays-$pkgver.tar.xz
16746901b71655898064984c4d1bd0fd  purpose-$pkgver.tar.xz
fdda5ee07fd893bca10b6e6c62ad4965  syndication-$pkgver.tar.xz
599b10ad4a5d110e996b6528b5165aeb  kcalendarcore-$pkgver.tar.xz
8f4e3826b4202ad0b006a7df67b0732e  kcontacts-$pkgver.tar.xz
714cedd448a555befc8da387ab5105b2  kquickcharts-$pkgver.tar.xz
766ddc42f378a4c69bf8bf9cedc18108  kdav-$pkgver.tar.xz
EOF

    export QT5PREFIX=/opt/qt5
    export KF5_PREFIX=/usr
    
    as_root()
    {
      if   [ $EUID = 0 ];        then $*
      elif [ -x /usr/bin/sudo ]; then sudo $*
      else                            su -c \\"$*\\"
      fi
    }

    export -f as_root

    bash -e

    while read -r line; do

        # Get the file name, ignoring comments and blank lines
        if $(echo $line | grep -E -q '^ *$|^#' ); then continue; fi
        file=$(echo $line | cut -d" " -f2)

        pkg=$(echo $file|sed 's|^.*/||')          # Remove directory
        packagedir=$(echo $pkg|sed 's|\.tar.*||') # Package directory

        name=$(echo $pkg|sed 's|-5.*$||') # Isolate package name

        tar -xf $file
        pushd $packagedir

          case $name in
            kitemviews*) sed -i '/<QList>/a #include <QPersistentModelIndex>' \
              src/kwidgetitemdelegatepool_p.h ;;
            kplotting*) sed -i '/<QHash>/a #include <QHelpEvent>' \
              src/kplotwidget.cpp ;;
            knotifica*) sed -i '/<QUrl>/a #include <QVariant>' \
              src/knotification.h ;;
            kcompleti*) sed -i '/<QClipboard>/a #include <QKeyEvent>' \
              src/klineedit.cpp ;;
            kwayland*) sed -i '/<wayland-xdg-output-server-proto/a #include <QHash>' \
              src/server/xdgoutput_interface.cpp ;;
            purpose*) sed -i 's/15,/16,/' \
              src/externalprocess/purposeprocess_main.cpp ;;
          esac  

          mkdir build
          cd    build

          cmake -DCMAKE_INSTALL_PREFIX=$KF5_PREFIX \
                -DCMAKE_PREFIX_PATH=$QT5DIR        \
                -DCMAKE_BUILD_TYPE=Release         \
                -DBUILD_TESTING=OFF                \
                -Wno-dev ..
          make
          as_root make install
        popd

      as_root rm -rf $packagedir
      as_root /sbin/ldconfig

    done < frameworks-$pkgver.md5

    exit

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
