#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=python3-mako
pkgver=1.1.3

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/Mako-$pkgver.tar.* -C $TMP

{ time \
   {

    cd $TMP/Mako-$pkgver

    python3 setup.py install --optimize=1

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
