#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=python3-pygobject
pkgver=3.38.0

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/pygobject-$pkgver.tar.* -C $TMP

{ time \
   {

    cd $TMP/pygobject-$pkgver

    mkdir build
    cd    build

    meson --prefix=/usr ..
    ninja

    ninja install

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
