#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=python3-pycairo
pkgver=1.20.0

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/pycairo-$pkgver.tar.* -C $TMP

{ time \
   {

    cd $TMP/pycairo-$pkgver

    python3 setup.py build

    python3 setup.py install --optimize=1  
    python3 setup.py install_pycairo_header
    python3 setup.py install_pkgconfig

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
