#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=python
pkgver=3.9.0

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/Python-$pkgver.tar.* -C $TMP

{ time \
   {

   cd $TMP/Python-$pkgver

    CXX="/usr/bin/g++"                              \
    ./configure --prefix=/usr                       \
                --enable-shared                     \
                --with-computed-gotos               \
                --enable-optimizations              \
                --with-lto                          \
                --enable-ipv6                       \
                --with-system-expat                 \
                --with-dbmliborder=gdbm:ndbm        \
                --with-system-ffi                   \
                --with-system-libmpdec              \
                --enable-loadable-sqlite-extensions \
                --without-ensurepip                 \
                --with-tzpath=/usr/share/zoneinfo

    make

    make install

    ln -svfn $pkgname-$pkgver /usr/share/doc/python-3

    cat > /etc/profile.d/pythondocs.sh << "EOF"
export PYTHONDOCS=/usr/share/doc/python-3/html
EOF
    . /etc/profile.d/pythondocs.sh

   }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
