#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=python3-pyyaml
pkgver=5.3.1

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/PyYAML-$pkgver.tar.* -C $TMP

{ time \
   {

   cd $TMP/PyYAML-$pkgver

    python3 setup.py build

    python3 setup.py install --optimize=1

   }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
