#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=qca
pkgver=2.3.1

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/$pkgname-$pkgver.tar.* -C $TMP

{ time \
   {

    cd $TMP/$pkgname-$pkgver
    
    export QT5DIR=/opt/qt5

    sed -i 's@cert.pem@certs/ca-bundle.crt@' CMakeLists.txt

    mkdir build
    cd    build

    cmake -DCMAKE_INSTALL_PREFIX=$QT5DIR            \
          -DCMAKE_BUILD_TYPE=Release                \
          -DQCA_MAN_INSTALL_DIR:PATH=/usr/share/man \
          ..
    make

    make install

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
