#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=rsync
pkgver=3.2.3

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/$pkgname-$pkgver.tar.* -C $TMP

{ time \
   {

   cd $TMP/$pkgname-$pkgver

    groupadd -g 48 rsyncd
    useradd -c "rsyncd Daemon" -d /home/rsync -g rsyncd \
        -s /bin/false -u 48 rsyncd

    ./configure --prefix=/usr    \
                --disable-lz4    \
                --disable-xxhash \
                --without-included-zlib
    make

    make install

    cat > /etc/rsyncd.conf << "EOF"
# This is a basic rsync configuration file
# It exports a single module without user authentication.

motd file = /home/rsync/welcome.msg
use chroot = yes

[localhost]
    path = /home/rsync
    comment = Default rsync module
    read only = yes
    list = yes
    uid = rsyncd
    gid = rsyncd

EOF
    
    tar xf $SRC/blfs-systemd-units-20200828.tar.xz
    cd blfs-systemd-units-20200828
    make install-rsyncd


   }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
