#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=sassc
pkgver=3.6.1

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/$pkgname-$pkgver.tar.* -C $TMP

{ time \
   {

    cd $TMP/$pkgname-$pkgver

    tar -xf $SRC/libsass-3.6.4.tar.gz
    pushd libsass-3.6.4

    autoreconf -fi

    ./configure --prefix=/usr --disable-static
    make

    make install

    popd
    autoreconf -fi

    ./configure --prefix=/usr
    make

    make install

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
