#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=sdl
pkgver=1.2.15

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/SDL-$pkgver.tar.* -C $TMP

{ time \
   {

    cd $TMP/SDL-$pkgver

    sed -e '/_XData32/s:register long:register _Xconst long:' \
        -i src/video/x11/SDL_x11sym.h

    ./configure --prefix=/usr --disable-static

    make

    make install

    install -v -m755 -d /usr/share/doc/SDL-$pkgver/html
    install -v -m644    docs/html/*.html \
                        /usr/share/doc/SDL-$pkgver/html

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
