#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=sdl2
pkgver=2.0.12

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/SDL2-$pkgver.tar.* -C $TMP

{ time \
   {

    cd $TMP/SDL2-$pkgver

    case $(uname -m) in
       i?86) patch -Np1 -i $SRC/SDL2-$pkgver-opengl_include_fix-1.patch ;;
    esac

    ./configure --prefix=/usr
    make

    make install             
    rm -v /usr/lib/libSDL2*.a

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
