#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=slang
pkgver=2.3.2

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/$pkgname-$pkgver.tar.* -C $TMP

{ time \
   {

    cd $TMP/$pkgname-$pkgver

    ./configure --prefix=/usr \
                --sysconfdir=/etc \
                --with-readline=gnu
    make -j1

    make install_doc_dir=/usr/share/doc/slang-2.3.2   \
         SLSH_DOC_DIR=/usr/share/doc/slang-2.3.2/slsh \
         install-all

    chmod -v 755 /usr/lib/libslang.so.2.3.2 \
                 /usr/lib/slang/v2/modules/*.so

    }

} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
