#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=sqlite
pkgver=3.34.0

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/sqlite-autoconf-3340000.tar.gz -C $TMP

{ time \
   {

    cd $TMP/sqlite-autoconf-3340000

    unzip -q $SRC/sqlite-doc-3340000.zip

    ./configure --prefix=/usr     \
                --disable-static  \
                --enable-fts5     \
                CFLAGS="-g -O2                    \
                -DSQLITE_ENABLE_FTS3=1            \
                -DSQLITE_ENABLE_FTS4=1            \
                -DSQLITE_ENABLE_COLUMN_METADATA=1 \
                -DSQLITE_ENABLE_UNLOCK_NOTIFY=1   \
                -DSQLITE_ENABLE_DBSTAT_VTAB=1     \
                -DSQLITE_SECURE_DELETE=1          \
                -DSQLITE_ENABLE_FTS3_TOKENIZER=1"
    make

    make install

    install -v -m755 -d /usr/share/doc/$pkgname-$pkgver
    cp -v -R sqlite-doc-3340000/* /usr/share/doc/$pkgname-$pkgver

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
