#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=unrar
pkgver=6.0.2

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/${pkgname}src-$pkgver.tar.* -C $TMP

{ time \
   {

   cd $TMP/$pkgname

    make -f makefile

    install -v -m755 unrar /usr/bin

   }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
