#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=unzip
pkgver=6.0

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/unzip60.tar.gz -C $TMP

{ time \
   {

    cd $TMP/${pkgname}60


    patch -Np1 -i $SRC/$pkgname-$pkgver-consolidated_fixes-1.patch

    make -f unix/Makefile generic

    make prefix=/usr MANDIR=/usr/share/man/man1 \
         -f unix/Makefile install

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
