#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=wpa_supplicant
pkgver=2.9

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/$pkgname-$pkgver.tar.* -C $TMP

{ time \
   {

    cd $TMP/$pkgname-$pkgver

    cat > wpa_supplicant/.config << "EOF"
CONFIG_BACKEND=file
CONFIG_CTRL_IFACE=y
CONFIG_DEBUG_FILE=y
CONFIG_DEBUG_SYSLOG=y
CONFIG_DEBUG_SYSLOG_FACILITY=LOG_DAEMON
CONFIG_DRIVER_NL80211=y
CONFIG_DRIVER_WEXT=y
CONFIG_DRIVER_WIRED=y
CONFIG_EAP_GTC=y
CONFIG_EAP_LEAP=y
CONFIG_EAP_MD5=y
CONFIG_EAP_MSCHAPV2=y
CONFIG_EAP_OTP=y
CONFIG_EAP_PEAP=y
CONFIG_EAP_TLS=y
CONFIG_EAP_TTLS=y
CONFIG_IEEE8021X_EAPOL=y
CONFIG_IPV6=y
CONFIG_LIBNL32=y
CONFIG_PEERKEY=y
CONFIG_PKCS12=y
CONFIG_READLINE=y
CONFIG_SMARTCARD=y
CONFIG_WPS=y
CFLAGS += -I/usr/include/libnl3
EOF

    cat >> wpa_supplicant/.config << "EOF"
CONFIG_CTRL_IFACE_DBUS=y
CONFIG_CTRL_IFACE_DBUS_NEW=y
CONFIG_CTRL_IFACE_DBUS_INTRO=y
EOF

    cd wpa_supplicant
    make BINDIR=/sbin LIBDIR=/lib

    pushd wpa_gui-qt4
    qmake wpa_gui.pro
    make
    popd

    install -v -m755 wpa_{cli,passphrase,supplicant} /sbin/
    install -v -m644 doc/docbook/wpa_supplicant.conf.5 /usr/share/man/man5/
    install -v -m644 doc/docbook/wpa_{cli,passphrase,supplicant}.8 /usr/share/man/man8/

    install -v -m644 systemd/*.service /lib/systemd/system/

    install -v -m644 dbus/fi.w1.wpa_supplicant1.service \
                     /usr/share/dbus-1/system-services/
    install -v -d -m755 /etc/dbus-1/system.d
    install -v -m644 dbus/dbus-wpa_supplicant.conf \
                     /etc/dbus-1/system.d/wpa_supplicant.conf

    systemctl enable wpa_supplicant
    
    install -v -m755 wpa_gui-qt4/wpa_gui /usr/bin/
    install -v -m644 doc/docbook/wpa_gui.8 /usr/share/man/man8/
    install -v -m644 wpa_gui-qt4/wpa_gui.desktop /usr/share/applications/
    install -v -m644 wpa_gui-qt4/icons/wpa_gui.svg /usr/share/pixmaps/

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
