#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/sources}

pkgname=xapian
pkgver=1.4.17

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/$pkgname-core-$pkgver.tar.* -C $TMP

{ time \
   {

   cd $TMP/$pkgname-core-$pkgver

    ./configure --prefix=/usr    \
                --disable-static \
                --docdir=/usr/share/doc/$pkgname-core-$pkgver
    make

    make install

   }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
