#!/bin/bash 
set -e

TMP=${TMP:-$/tmp/work}
LOG=${LOG:-$HOME/logs/stage3}
SRC=${SRC:-/sources}

name=expat
version=2.2.10

mkdir -p $TMP $LOG

tar xf $SRC/$name-$version.tar.xz -C $TMP

{ time \
   {

    cd $TMP/$name-$version
    
	./configure --prefix=/usr    \
				--disable-static \
				--docdir=/usr/share/doc/$name-$version
    
    make
    
    make install
    
    install -v -m644 doc/*.{html,png,css} /usr/share/doc/$name-$version

    }
} 2>&1 | tee $name.log
    
[ $PIPESTATUS = 0 ] && mv $name.log $LOG || exit $PIPESTATUS

rm -fr $TMP
