#!/bin/bash 
set -e

TMP=${TMP:-$/tmp/work}
LOG=${LOG:-$HOME/logs/stage3}
SRC=${SRC:-/sources}

name=gawk
version=5.1.0

mkdir -p $TMP $LOG

tar xf $SRC/$name-$version.tar.xz -C $TMP

{ time \
   {

    cd $TMP/$name-$version
    
    sed -i 's/extras//' Makefile.inn
    
    ./configure --prefix=/usr
    
    make
    
    make install
    
    mkdir -v /usr/share/doc/$name-$version
    cp    -v doc/{awkforai.txt,*.{eps,pdf,jpg}} /usr/share/doc/$name-$version

    }
} 2>&1 | tee $name.log
    
[ $PIPESTATUS = 0 ] && mv $name.log $LOG || exit $PIPESTATUS

rm -fr $TMP
