#!/bin/bash 
set -e

TMP=${TMP:-$/tmp/work}
LOG=${LOG:-$HOME/logs/stage3}
SRC=${SRC:-/sources}

name=intltool
version=0.51.0

mkdir -p $TMP $LOG

tar xf $SRC/$name-$version.tar.gz -C $TMP

{ time \
   {

    cd $TMP/$name-$version
    
    sed -i 's:\\\${:\\\$\\{:' intltool-update.in
    
    ./configure --prefix=/usr
    
    make
    
    make install
    install -v -Dm644 doc/I18N-HOWTO /usr/share/doc/$name-$version/I18N-HOWTO

    }
} 2>&1 | tee $name.log
    
[ $PIPESTATUS = 0 ] && mv $name.log $LOG || exit $PIPESTATUS

rm -fr $TMP
