#!/bin/bash 
set -e


TMP=${TMP:-/tmp/work}
LOG=${LOG:-$HOME/logs/stage4}
SRC=${SRC:-/sources}

name=libassuan
version=2.5.4

rm -rf $TMP
mkdir -p $TMP $LOG

tar xf $SRC/$name-$version.tar.bz2 -C $TMP

{ time \
   {

    cd $TMP/$name-$version
    
	./configure --prefix=/usr
	make

	make -C doc html
	makeinfo --html --no-split -o doc/assuan_nochunks.html doc/assuan.texi
	makeinfo --plaintext       -o doc/assuan.txt           doc/assuan.texi

	make instal

	install -v -dm755   /usr/share/doc/$name-$version/html
	install -v -m644 doc/assuan.html/* \
	                    /usr/share/doc/$name-$version/html
	install -v -m644 doc/assuan_nochunks.html \
	                    /usr/share/doc/$name-$version
	install -v -m644 doc/assuan.{txt,texi} \
	                    /usr/share/doc/$name-$version

    }
} 2>&1 | tee $name.log
    
[ $PIPESTATUS = 0 ] && mv $name.log $LOG || exit $PIPESTATUS

rm -fr $TMP
