#!/bin/bash
set -e


TMP=${TMP:-$(dirname $0)/Build-TMP}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-$/sources}

pkgname=python3
pkgver=3.8.6

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/Python-$pkgver.tar.xz -C $TMP

{ time \
   {

    cd $TMP/Python-$pkgver
   ./configure --prefix=/usr   \
               --enable-shared \
               --without-ensurepip
    make
    make install
    
    }
} 2>&1 | tee $pkgname.log

[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
