#!/bin/bash 
set -e


TMP=${TMP:-/tmp/work}
LOG=${LOG:-$HOME/logs/stage4}
SRC=${SRC:-/sources}

name=asciidoc
version=9.0.5

rm -rf $TMP
mkdir -p $TMP $LOG

tar xf $SRC/$name-$version.tar.gz -C $TMP

{ time \
   {

    cd $TMP/$name-$version
    
	sed -i 's:doc/testasciidoc.1::' Makefile.in
	rm doc/testasciidoc.1.txt

	./configure --prefix=/usr     \
	            --sysconfdir=/etc \
	            --docdir=/usr/share/doc/$name-$version
	make

	make install
	make docs

    }
} 2>&1 | tee $name.log
    
[ $PIPESTATUS = 0 ] && mv $name.log $LOG || exit $PIPESTATUS

rm -fr $TMP
