#!/bin/bash 
set -e


TMP=${TMP:-/tmp/work}
LOG=${LOG:-$HOME/logs/stage4}
SRC=${SRC:-$LFS/sources}

name=dracut
version=051

mkdir -p $TMP $LOG

tar xf $SRC/$name-$version.tar.gz -C $TMP

{ time \
   {

    cd $TMP/$name-$version
    
    ./configure --sysconfdir=/etc \
                --prefix=/usr     \
                --libdir=/usr/lib \
                --systemdsystemunitdir=/usr/lib/systemd/system \
                --bashcompletiondir=$(pkg-config --variable=completionsdir bash-completion)
    make
    make install 

    }
} 2>&1 | tee $name.log
    
[ $PIPESTATUS = 0 ] && mv $name.log $LOG || exit $PIPESTATUS

rm -fr $TMP
