#!/bin/bash 
set -e


TMP=${TMP:-/tmp/work}
LOG=${LOG:-$HOME/logs/stage4}
SRC=${SRC:-/sources}

name=libpng
version=1.6.37

rm -rf $TMP
mkdir -p $TMP $LOG

tar xf $SRC/$name-$version.tar.xz -C $TMP

{ time \
   {

    cd $TMP/$name-$version
    
	gzip -cd $SRC/$name-$version-apng.patch.gz | patch -p1

	./configure --prefix=/usr --disable-static
	make

	make install
	mkdir -v /usr/share/doc/$name-$version
	cp -v README libpng-manual.txt /usr/share/doc/$name-$version

    }
} 2>&1 | tee $name.log
    
[ $PIPESTATUS = 0 ] && mv $name.log $LOG || exit $PIPESTATUS

rm -fr $TMP
