#!/bin/bash 
set -e


TMP=${TMP:-/tmp/work}
LOG=${LOG:-$HOME/logs/stage4}
SRC=${SRC:-$LFS/sources}

name=python3-imagesize
version=1.2.0

mkdir -p $TMP $LOG

tar xf $SRC/imagesize-$version.tar.gz -C $TMP

{ time \
   {

    cd $TMP/imagesize-$version
    
	python3 setup.py install --optimize=1
    
    }
} 2>&1 | tee $name.log
    
[ $PIPESTATUS = 0 ] && mv $name.log $LOG || exit $PIPESTATUS

rm -fr $TMP
