#!/bin/bash 
set -e


TMP=${TMP:-$/tmp/work}
LOG=${LOG:-$HOME/logs/stage4}
SRC=${SRC:-$LFS/sources}

name=python3-sphinxcontrib-devhelp
version=1.0.2

mkdir -p $TMP $LOG

tar xf $SRC/sphinxcontrib-devhelp-$version.tar.gz -C $TMP

{ time \
   {

    cd $TMP/sphinxcontrib-devhelp-$version
    
	python3 setup.py install --optimize=1
    
    }
} 2>&1 | tee $name.log
    
[ $PIPESTATUS = 0 ] && mv $name.log $LOG || exit $PIPESTATUS

rm -fr $TMP
