#!/bin/bash 
set -e


TMP=${TMP:-/tmp/work}
LOG=${LOG:-$HOME/logs/stage4}
SRC=${SRC:-/sources}

name=python3-lxml
version=4.6.2

mkdir -p $TMP $LOG

tar xf $SRC/lxml-$version.tar.gz -C $TMP

{ time \
   {

    cd $TMP/lxml-$version

    python3 setup.py build

    python3 setup.py install --optimize=1 


    }
} 2>&1 | tee $name.log
    
[ $PIPESTATUS = 0 ] && mv $name.log $LOG || exit $PIPESTATUS

rm -fr $TMP
