#!/bin/bash 
set -e


TMP=${TMP:-/tmp/work}
LOG=${LOG:-$HOME/logs/stage4}
SRC=${SRC:-/sources}

name=python3-babel
version=2.9.0

rm -rf $TMP
mkdir -p $TMP $LOG

# http://unicode.org/Public/cldr/37/core.zip
tar xf $SRC/${name/python3-/}-$version.tar.gz -C $TMP

{ time \
   {

    cd $TMP/${name/python3-/}-$version
    
    cp core.zip cldr/cldr-core-37.zip
    
    python3 setup.py import_cldr
    python3 setup.py build
    
    python3 setup.py install --optimize=1

    }
} 2>&1 | tee $name.log
    
[ $PIPESTATUS = 0 ] && mv $name.log $LOG || exit $PIPESTATUS

rm -fr $TMP
