#!/bin/bash 
set -e


TMP=${TMP:-/tmp/work}
LOG=${LOG:-$HOME/logs/stage4}
SRC=${SRC:-$LFS/sources}

name=python3-pygments
version=2.7.4

mkdir -p $TMP $LOG

tar xf $SRC/Pygments-$version.tar.xz -C $TMP

{ time \
   {

    cd $TMP/Pygments-$version
    
    python3 setup.py install --optimize=1

    }
} 2>&1 | tee $name.log
    
[ $PIPESTATUS = 0 ] && mv $name.log $LOG || exit $PIPESTATUS

rm -fr $TMP
