#!/bin/bash  -e


TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/blfs-sources}
BUILDDIR=${BUILDDIR:-$(dirname $0)/build}

pkgbase=berkeley-db
name=db
version=5.3.28

rm -fr $TMP
mkdir -p $TMP $LOG $SRC $BUILDDIR

tar xf $SRC/$name-$version.tar.* -C $TMP
 
{ time \
   {

    cd $TMP/$name-$version

    sed -i 's/\(__atomic_compare_exchange\)/\1_db/' src/dbinc/atomic.h

	cd build_unix
	../dist/configure --prefix=/usr      \
					--enable-compat185 \
					--enable-dbm       \
					--disable-static   \
					--enable-cxx
	make

	make docdir=/usr/share/doc/db-$version install

	chown -v -R root:root                        \
		/usr/bin/db_*                          \
		/usr/include/db{,_185,_cxx}.h          \
		/usr/lib/libdb*.{so,la}                \
		/usr/share/doc/db-$version

    }
} 2>&1 | tee $LOG/$pkgbase.log

[ $PIPESTATUS = 0 ] && echo "$name-$version" > $BUILDDIR/$pkgbase || exit $PIPESTATUS

rm -fr $TMP 
