#!/bin/bash  -e


TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/blfs-sources}
BUILDDIR=${BUILDDIR:-$(dirname $0)/build}

name=blfs-systemd-units
version=20200415

rm -fr $TMP
mkdir -p $TMP $LOG $SRC $BUILDDIR

tar xf $SRC/$name-$version.tar.* -C $TMP
 
{ time \
   {

    cd $TMP/$name-$version

    # http://www.linuxfromscratch.org/blfs/view/systemd/postlfs/openssh.html
    make install-sshd

    # http://www.linuxfromscratch.org/blfs/view/systemd/postlfs/cyrus-sasl.html
    make install-saslauthd

    # http://www.linuxfromscratch.org/blfs/view/systemd/server/openldap.html
    make install-slapd

    systemctl start slapd

    # http://www.linuxfromscratch.org/blfs/view/systemd/postlfs/mitkrb.html
    #make install-krb5

    # http://www.linuxfromscratch.org/blfs/view/systemd/general/gpm.html
    make install-gpm
    
    # http://www.linuxfromscratch.org/blfs/view/systemd/basicnet/rsync.html
    make install-rsyncd

    }
} 2>&1 | tee $LOG/$name.log

[ $PIPESTATUS = 0 ] && echo "$name-$version" > $BUILDDIR/$name || exit $PIPESTATUS

rm -fr $TMP 
