#!/bin/bash 
set -e
 
TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/blfs-sources}
BUILDLOG=${BUILDLOG:-$(dirname $0)/build}
 
name=boost
version=1_73_0
_version=1.73.0
 
rm -fr $TMP
mkdir -p $TMP $LOG $SRC  $BUILDLOG
 
tar xf $SRC/${name}_${version}.tar.* -C $TMP
 
{ time \
   {
 
    cd $TMP/${name}_${version}

    patch -Np1 -i $SRC/boost-$_version-gcc_10-1.patch

    ./bootstrap.sh --prefix=/usr --with-python=python3
    ./b2 stage -j$(nproc) threading=multi link=shared

    ./b2 install threading=multi link=shared
    ln -svf detail/sha1.hpp /usr/include/boost/uuid/sha1.hpp

    }   
} 2>&1 | tee $LOG/$name.log
    
[ $PIPESTATUS = 0 ] && echo "$name-$version" > $BUILDLOG/$name || exit $PIPESTATUS

rm -fr $TMP	
	

