#!/bin/bash 
set -e
 
TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/blfs-sources}
BUILDLOG=${BUILDLOG:-$(dirname $0)/build}
 
name=cmake
version=3.17.3
 
rm -fr $TMP
mkdir -p $TMP $LOG $SRC  $BUILDLOG
 
tar xf $SRC/$name-$version.tar.* -C $TMP
 
{ time \
   {
 
    cd $TMP/$name-$version

	sed -i '/"lib64"/s/64//' Modules/GNUInstallDirs.cmake

	./bootstrap --prefix=/usr        \
				--system-libs        \
				--mandir=/share/man  \
				--no-system-jsoncpp  \
				--no-system-librhash \
				--docdir=/share/doc/cmake-$version
	make

	make install

    }   
} 2>&1 | tee $LOG/$name.log
    
[ $PIPESTATUS = 0 ] && echo "$name-$version" > $BUILDLOG/$name || exit $PIPESTATUS

rm -fr $TMP	
	

