#!/bin/bash  -e


TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/blfs-sources}
BUILDDIR=${BUILDDIR:-$(dirname $0)/build}

name=cyrus-sasl
version=2.1.27

rm -fr $TMP
mkdir -p $TMP $LOG $SRC $BUILDDIR

tar xf $SRC/$name-$version.tar.* -C $TMP
 
{ time \
   {

    cd $TMP/$name-$version

    patch -Np1 -i $SRC/cyrus-sasl-$version-doc_fixes-1.patch

	./configure --prefix=/usr        \
				--sysconfdir=/etc    \
				--enable-auth-sasldb \
                --with-dblib=gdbm    \
                --enable-login       \
                --with-ldap          \
                --enable-ldapdb      \
                --with-pam           \
                --enable-ntlm        \
				--with-dbpath=/var/lib/sasl/sasldb2 \
				--with-saslauthd=/var/run/saslauthd
	make -j1

	make install
	install -v -dm755                          /usr/share/doc/cyrus-sasl$version/html
	install -v -m644  saslauthd/LDAP_SASLAUTHD /usr/share/doc/cyrus-sasl$version
	install -v -m644  doc/legacy/*.html        /usr/share/doc/cyrus-sasl$version/html
	install -v -dm700 /var/lib/sasl

    }
} 2>&1 | tee $LOG/$name.log

[ $PIPESTATUS = 0 ] && echo "$name-$version" > $BUILDDIR/$name || exit $PIPESTATUS

rm -fr $TMP 
