#!/bin/bash  -e


TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/blfs-sources}
BUILDDIR=${BUILDDIR:-$(dirname $0)/build}

pkgbase=dbus-python3
name=dbus-python
version=1.2.16

rm -fr $TMP
mkdir -p $TMP $LOG $SRC $BUILDDIR

tar xf $SRC/$name-$version.tar.* -C $TMP
 
{ time \
   {

    cd $TMP/$name-$version

	mkdir python3 
	pushd python3 
		PYTHON=/usr/bin/python3    \
		../configure --prefix=/usr --docdir=/usr/share/doc/dbus-python-$version
		make 
	popd

	make -C python3 install

    }
} 2>&1 | tee $LOG/$pkgbase.log

[ $PIPESTATUS = 0 ] && echo "$name-$version" > $BUILDDIR/$pkgbase || exit $PIPESTATUS

rm -fr $TMP 
