#!/bin/bash 
set -e
 
TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/blfs-sources}
BUILDLOG=${BUILDLOG:-$(dirname $0)/build}
 
name=docbook-xml
version=4.5
 
rm -fr $TMP
mkdir -p $TMP $LOG $SRC  $BUILDLOG
 
tar xf $SRC/$name-$version.tar.* -C $TMP
 
{ time \
   {
 
    cd $TMP/$name-$version

	install -v -d -m755 /usr/share/xml/docbook/xml-dtd-$version
	install -v -d -m755 /etc/xml
	chown -R root:root .
	cp -v -af docbook.cat *.dtd ent/ *.mod \
		/usr/share/xml/docbook/xml-dtd-$version

	if [ ! -e /etc/xml/docbook ]; then
		xmlcatalog --noout --create /etc/xml/docbook
	fi
	xmlcatalog --noout --add "public" \
		"-//OASIS//DTD DocBook XML V$version//EN" \
		"http://www.oasis-open.org/docbook/xml/$version/docbookx.dtd" \
		/etc/xml/docbook
	xmlcatalog --noout --add "public" \
		"-//OASIS//DTD DocBook XML CALS Table Model V$version//EN" \
		"file:///usr/share/xml/docbook/xml-dtd-$version/calstblx.dtd" \
		/etc/xml/docbook
	xmlcatalog --noout --add "public" \
		"-//OASIS//DTD XML Exchange Table Model 19990315//EN" \
		"file:///usr/share/xml/docbook/xml-dtd-$version/soextblx.dtd" \
		/etc/xml/docbook
	xmlcatalog --noout --add "public" \
		"-//OASIS//ELEMENTS DocBook XML Information Pool V$version//EN" \
		"file:///usr/share/xml/docbook/xml-dtd-$version/dbpoolx.mod" \
		/etc/xml/docbook
	xmlcatalog --noout --add "public" \
		"-//OASIS//ELEMENTS DocBook XML Document Hierarchy V$version//EN" \
		"file:///usr/share/xml/docbook/xml-dtd-$version/dbhierx.mod" \
		/etc/xml/docbook
	xmlcatalog --noout --add "public" \
		"-//OASIS//ELEMENTS DocBook XML HTML Tables V$version//EN" \
		"file:///usr/share/xml/docbook/xml-dtd-$version/htmltblx.mod" \
		/etc/xml/docbook
	xmlcatalog --noout --add "public" \
		"-//OASIS//ENTITIES DocBook XML Notations V$version//EN" \
		"file:///usr/share/xml/docbook/xml-dtd-$version/dbnotnx.mod" \
		/etc/xml/docbook
	xmlcatalog --noout --add "public" \
		"-//OASIS//ENTITIES DocBook XML Character Entities V$version//EN" \
		"file:///usr/share/xml/docbook/xml-dtd-$version/dbcentx.mod" \
		/etc/xml/docbook
	xmlcatalog --noout --add "public" \
		"-//OASIS//ENTITIES DocBook XML Additional General Entities V$version//EN" \
		"file:///usr/share/xml/docbook/xml-dtd-$version/dbgenent.mod" \
		/etc/xml/docbook
	xmlcatalog --noout --add "rewriteSystem" \
		"http://www.oasis-open.org/docbook/xml/$version" \
		"file:///usr/share/xml/docbook/xml-dtd-$version" \
		/etc/xml/docbook
	xmlcatalog --noout --add "rewriteURI" \
		"http://www.oasis-open.org/docbook/xml/$version" \
		"file:///usr/share/xml/docbook/xml-dtd-$version" \
		/etc/xml/docbook
	
    if [ ! -e /etc/xml/catalog ]; then
    	xmlcatalog --noout --create /etc/xml/catalog
	fi
	xmlcatalog --noout --add "delegatePublic" \
		"-//OASIS//ENTITIES DocBook XML" \
		"file:///etc/xml/docbook" \
		/etc/xml/catalog
	xmlcatalog --noout --add "delegatePublic" \
		"-//OASIS//DTD DocBook XML" \
		"file:///etc/xml/docbook" \
		/etc/xml/catalog
	xmlcatalog --noout --add "delegateSystem" \
		"http://www.oasis-open.org/docbook/" \
		"file:///etc/xml/docbook" \
		/etc/xml/catalog
	xmlcatalog --noout --add "delegateURI" \
		"http://www.oasis-open.org/docbook/" \
		"file:///etc/xml/docbook" \
		/etc/xml/catalog

    for DTDVERSION in 4.1.2 4.2 4.3 4.4; do
		xmlcatalog --noout --add "public" \
			"-//OASIS//DTD DocBook XML V$DTDVERSION//EN" \
			"http://www.oasis-open.org/docbook/xml/$DTDVERSION/docbookx.dtd" \
			/etc/xml/docbook
		xmlcatalog --noout --add "rewriteSystem" \
			"http://www.oasis-open.org/docbook/xml/$DTDVERSION" \
			"file:///usr/share/xml/docbook/xml-dtd-4.5" \
			/etc/xml/docbook
		xmlcatalog --noout --add "rewriteURI" \
			"http://www.oasis-open.org/docbook/xml/$DTDVERSION" \
			"file:///usr/share/xml/docbook/xml-dtd-4.5" \
			/etc/xml/docbook
		xmlcatalog --noout --add "delegateSystem" \
			"http://www.oasis-open.org/docbook/xml/$DTDVERSION/" \
			"file:///etc/xml/docbook" \
			/etc/xml/catalog
		xmlcatalog --noout --add "delegateURI" \
			"http://www.oasis-open.org/docbook/xml/$DTDVERSION/" \
			"file:///etc/xml/docbook" \
			/etc/xml/catalog
	done

    }   
} 2>&1 | tee $LOG/$name.log
    
[ $PIPESTATUS = 0 ] && echo "$name-$version" > $BUILDLOG/$name || exit $PIPESTATUS

rm -fr $TMP	
	

