#!/bin/bash  -e


TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/blfs-sources}
BUILDDIR=${BUILDDIR:-$(dirname $0)/build}

name=dracut
version=050

rm -fr $TMP
mkdir -p $TMP $LOG $SRC $BUILDDIR

tar xf $SRC/$name-$version.tar.* -C $TMP
 
{ time \
   {

    cd $TMP/$name-$version

	./configure --prefix=/usr

	make sysconfdir=/etc

	make install sbindir=/sbin sysconfdir=/etc

    }
} 2>&1 | tee $LOG/$name.log

[ $PIPESTATUS = 0 ] && echo "$name" > $BUILDDIR/$name || exit $PIPESTATUS

rm -fr $TMP 
