#!/bin/bash 
set -e
 
TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/blfs-sources}
BUILDLOG=${BUILDLOG:-$(dirname $0)/build}
 
name=fontconfig
version=2.13.1
 
rm -fr $TMP
mkdir -p $TMP $LOG $SRC  $BUILDLOG
 
tar xf $SRC/$name-$version.tar.* -C $TMP
 
{ time \
   {
 
    cd $TMP/$name-$version

    rm -f src/fcobjshash.h

    ./configure --prefix=/usr        \
            --sysconfdir=/etc    \
            --localstatedir=/var \
            --disable-docs       \
            --docdir=/usr/share/doc/fontconfig-$version
	make

	make install

	install -v -dm755 \
			/usr/share/{man/man{1,3,5},doc/fontconfig-$version/fontconfig-devel}
	install -v -m644 fc-*/*.1         /usr/share/man/man1
	install -v -m644 doc/*.3          /usr/share/man/man3
	install -v -m644 doc/fonts-conf.5 /usr/share/man/man5
	install -v -m644 doc/fontconfig-devel/* \
									/usr/share/doc/fontconfig-$version/fontconfig-devel
	install -v -m644 doc/*.{pdf,sgml,txt,html} \
									/usr/share/doc/fontconfig-$version


    }   
} 2>&1 | tee $LOG/$name.log
    
[ $PIPESTATUS = 0 ] && echo "$name-$version" > $BUILDLOG/$name || exit $PIPESTATUS

rm -fr $TMP	
	

