#!/bin/bash 
set -e
 
TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/blfs-sources}
BUILDLOG=${BUILDLOG:-$(dirname $0)/build}
 
name=freetype
version=2.10.2
 
rm -fr $TMP
mkdir -p $TMP $LOG $SRC  $BUILDLOG
 
tar xf $SRC/$name-$version.tar.* -C $TMP
 
{ time \
   {
 
    cd $TMP/$name-$version

    tar -xf $SRC/freetype-doc-$version.tar.xz --strip-components=2 -C docs

    sed -ri "s:.*(AUX_MODULES.*valid):\1:" modules.cfg

	sed -r "s:.*(#.*SUBPIXEL_RENDERING) .*:\1:" \
	    -i include/freetype/config/ftoption.h

	./configure --prefix=/usr    \
        --enable-freetype-config \
        --disable-static         \
        --without-harfbuzz
	make

	make install

	install -v -m755 -d /usr/share/doc/freetype-$version
	cp -v -R docs/*     /usr/share/doc/freetype-$version
	rm -v /usr/share/doc/freetype-$version/freetype-config.1

    }   
} 2>&1 | tee $LOG/$name.log
    
[ $PIPESTATUS = 0 ] && echo "$name-$version" > $BUILDLOG/$name || exit $PIPESTATUS

rm -fr $TMP	
	

