#!/bin/bash  -e


TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/blfs-sources}
BUILDDIR=${BUILDDIR:-$(dirname $0)/build}

name=git
version=2.27.0

rm -fr $TMP
mkdir -p $TMP $LOG $SRC $BUILDDIR

tar xf $SRC/$name-$version.tar.* -C $TMP
 
{ time \
   {

    cd $TMP/$name-$version

	./configure --prefix=/usr \
            --with-gitconfig=/etc/gitconfig \
            --with-python=python3			\
			--with-libpcre                  \
            --enable-jit
	make

	make man

	make install

	make install-man

	make htmldir=/usr/share/doc/git-$version install-html

	tar -xf $SRC/git-manpages-$version.tar.xz \
	    -C /usr/share/man --no-same-owner --no-overwrite-dir

	mkdir -vp   /usr/share/doc/git-$version
	tar   -xf   $SRC/git-htmldocs-$version.tar.xz \
    	  -C    /usr/share/doc/git-$version --no-same-owner --no-overwrite-dir

	find        /usr/share/doc/git-$version -type d -exec chmod 755 {} \;
	find        /usr/share/doc/git-$version -type f -exec chmod 644 {} \;

	mkdir -vp /usr/share/doc/git-$version/man-pages/{html,text}
	mv        /usr/share/doc/git-$version/{git*.txt,man-pages/text}
	mv        /usr/share/doc/git-$version/{git*.,index.,man-pages/}html

	mkdir -vp /usr/share/doc/git-$version/technical/{html,text}
	mv        /usr/share/doc/git-$version/technical/{*.txt,text}
	mv        /usr/share/doc/git-$version/technical/{*.,}html

	mkdir -vp /usr/share/doc/git-$version/howto/{html,text}
	mv        /usr/share/doc/git-$version/howto/{*.txt,text}
	mv        /usr/share/doc/git-$version/howto/{*.,}html

	sed -i '/^<a href=/s|howto/|&html/|' /usr/share/doc/git-$version/howto-index.html
	sed -i '/^\* link:/s|howto/|&html/|' /usr/share/doc/git-$version/howto-index.txt


    }
} 2>&1 | tee $LOG/$name.log

[ $PIPESTATUS = 0 ] && echo "$name-$version" > $BUILDDIR/$name || exit $PIPESTATUS

rm -fr $TMP 
