#!/bin/bash 
set -e
 
TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/blfs-sources}
BUILDLOG=${BUILDLOG:-$(dirname $0)/build}
 
name=glib
version=2.64.3
 
rm -fr $TMP
mkdir -p $TMP $LOG $SRC  $BUILDLOG
 
tar xf $SRC/$name-$version.tar.* -C $TMP
 
{ time \
   {
 
    cd $TMP/$name-$version

    patch -Np1 -i $SRC/glib-$version-skip_warnings-1.patch

	mkdir build
	cd    build

	meson --prefix=/usr      \
		-Dman=true         \
		-Dselinux=disabled \
		-Ddoc=true         \
		..
	ninja

	ninja install

	mkdir -p /usr/share/doc/glib-$version
	cp -r ../docs/reference/{NEWS,gio,glib,gobject} /usr/share/doc/glib-$version

    }   
} 2>&1 | tee $LOG/$name.log
    
[ $PIPESTATUS = 0 ] && echo "$name-$version" > $BUILDLOG/$name || exit $PIPESTATUS

rm -fr $TMP	
	

