#!/bin/bash  -e


TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/blfs-sources}
BUILDDIR=${BUILDDIR:-$(dirname $0)/build}

name=gpm
version=1.20.7

rm -fr $TMP
mkdir -p $TMP $LOG $SRC $BUILDDIR

tar xf $SRC/$name-$version.tar.* -C $TMP
 
{ time \
   {

    cd $TMP/$name-$version

	patch -Np1 -i $SRC/gpm-$version-consolidated-1.patch
	./autogen.sh
	./configure --prefix=/usr --sysconfdir=/etc
	make

	make install 

	install-info --dir-file=/usr/share/info/dir           \
			/usr/share/info/gpm.info

	ln -sfv libgpm.so.2.1.0 /usr/lib/libgpm.so
	install -v -m644 conf/gpm-root.conf /etc 

	install -v -m755 -d /usr/share/doc/gpm-$version/support

	install -v -m644    doc/support/*                     \
			/usr/share/doc/gpm-$version/support
	install -v -m644    doc/{FAQ,HACK_GPM,README*}        \
			/usr/share/doc/gpm-$version

	install -v -dm755 /etc/systemd/system/gpm.service.d
	cat > /etc/systemd/system/gpm.service.d/99-user.conf << EOF
[Service]
ExecStart=/usr/sbin/gpm <list of parameters>
EOF

    }
} 2>&1 | tee $LOG/$name.log

[ $PIPESTATUS = 0 ] && echo "$name-$version" > $BUILDDIR/$name || exit $PIPESTATUS

rm -fr $TMP 
