#!/bin/bash 
set -e
 
TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/blfs-sources}
BUILDLOG=${BUILDLOG:-$(dirname $0)/build}
 
name=graphite2
version=1.3.14
 
rm -fr $TMP
mkdir -p $TMP $LOG $SRC  $BUILDLOG
 
tar xf $SRC/$name-$version.tgz -C $TMP
 
{ time \
   {
 
    cd $TMP/$name-$version
	
	mkdir build
	cd    build

	cmake -DCMAKE_INSTALL_PREFIX=/usr ..
	make

#	make docs

	make install

	install -v -d -m755 /usr/share/doc/graphite2-$version

#	cp      -v -f    doc/{GTF,manual}.html \
#						/usr/share/doc/graphite2-$version
#	cp      -v -f    doc/{GTF,manual}.pdf \
#						/usr/share/doc/graphite2-$version

    }   
} 2>&1 | tee $LOG/$name.log
    
[ $PIPESTATUS = 0 ] && echo "$name-$version" > $BUILDLOG/$name || exit $PIPESTATUS

rm -fr $TMP	
	

