#!/bin/bash  -e


TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/blfs-sources}
BUILDDIR=${BUILDDIR:-$(dirname $0)/build}

pkgbase=js
name=firefox
version=68.4.2

rm -fr $TMP
mkdir -p $TMP $LOG $SRC $BUILDDIR

tar xf $SRC/$name-${version}esr.source.tar.* -C $TMP
 
{ time \
   {

    cd $TMP/$name-$version

    patch -Np1 -i $SRC/js68-$version-python_3-1.patch

	sed '21,+4d' -i js/moz.configure

	mkdir -p obj
	cd    obj

	CC=gcc CXX=g++ LLVM_OBJDUMP=/bin/false       \
	../js/src/configure --prefix=/usr            \
						--with-intl-api          \
						--with-system-zlib       \
						--with-system-icu        \
						--disable-jemalloc       \
						--disable-debug-symbols  \
						--enable-readline        \
                        --enable-smoosh          \
						--enable-unaligned-private-values
	make

	make install
	rm -v /usr/lib/libjs_static.ajs

    }
} 2>&1 | tee $LOG/$name.log

[ $PIPESTATUS = 0 ] && echo "$name-$version" > $BUILDDIR/$name || exit $PIPESTATUS

rm -fr $TMP 
