#!/bin/bash  -e


TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/blfs-sources}
BUILDDIR=${BUILDDIR:-$(dirname $0)/build}

name=js-copy
#version=

rm -fr $TMP
mkdir -p $TMP $LOG $SRC $BUILDDIR

tar xf $SRC/js68-68.9.0-1-x86_64.pkg.tar.* -C $TMP
 
{ time \
   {

    cd $TMP
    
    cp -rv usr/* /usr/

    }
} 2>&1 | tee $LOG/$name.log

[ $PIPESTATUS = 0 ] && echo "$name-$version" > $BUILDDIR/$name || exit $PIPESTATUS

rm -fr $TMP 
