#!/bin/bash 
set -e
 
TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/blfs-sources}
BUILDLOG=${BUILDLOG:-$(dirname $0)/build}
 
name=libaio
version=0.3.112
 
rm -fr $TMP
mkdir -p $TMP $LOG $SRC  $BUILDLOG

tar xf $SRC/${name}_${version}.orig.tar.* -C $TMP
 
{ time \
   {
 
    cd $TMP/$name-$version
    
    sed -i '/install.*libaio.a/s/^/#/' src/Makefile

    make

    make install

    }   
} 2>&1 | tee $LOG/$name.log
    
[ $PIPESTATUS = 0 ] && echo "$name-$version" > $BUILDLOG/$name || exit $PIPESTATUS

rm -fr $TMP	
	

