#!/bin/bash  -e


TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/blfs-sources}
BUILDDIR=${BUILDDIR:-$(dirname $0)/build}

name=libgcrypt
version=1.8.5

rm -fr $TMP
mkdir -p $TMP $LOG $SRC $BUILDDIR

tar xf $SRC/$name-$version.tar.* -C $TMP
 
{ time \
   {

    cd $TMP/$name-$version

	./configure --prefix=/usr --with-capabilities
	make

	make -C doc html
	makeinfo --html --no-split -o doc/gcrypt_nochunks.html doc/gcrypt.texi
	makeinfo --plaintext       -o doc/gcrypt.txt           doc/gcrypt.texi

	make install
	install -v -dm755   /usr/share/doc/libgcrypt$version
	install -v -m644    README doc/{README.apichanges,fips*,libgcrypt*} \
						/usr/share/doc/libgcrypt$version

	install -v -dm755   /usr/share/doc/libgcrypt$version/html
	install -v -m644 doc/gcrypt.html/* \
						/usr/share/doc/libgcrypt$version/html
	install -v -m644 doc/gcrypt_nochunks.html \
						/usr/share/doc/libgcrypt$version
	install -v -m644 doc/gcrypt.{txt,texi} \
						/usr/share/doc/libgcrypt$version



    }
} 2>&1 | tee $LOG/$name.log

[ $PIPESTATUS = 0 ] && echo "$name-$version" > $BUILDDIR/$name || exit $PIPESTATUS

rm -fr $TMP 
