#!/bin/bash 
set -e
 
TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/blfs-sources}
BUILDLOG=${BUILDLOG:-$(dirname $0)/build}
 
name=libpng
version=1.6.37
 
rm -fr $TMP
mkdir -p $TMP $LOG $SRC  $BUILDLOG
 
tar xf $SRC/$name-$version.tar.* -C $TMP
 
{ time \
   {
 
    cd $TMP/$name-$version
    
    gzip -cd $SRC/libpng-$version-apng.patch.gz | patch -p1
    
	./configure --prefix=/usr --disable-static
	make

	make install
	mkdir -v /usr/share/doc/libpng-$version
	cp -v README libpng-manual.txt /usr/share/doc/libpng-$version

    }   
} 2>&1 | tee $LOG/$name.log
    
[ $PIPESTATUS = 0 ] && echo "$name-$version" > $BUILDLOG/$name || exit $PIPESTATUS

rm -fr $TMP	
	

