#!/bin/bash  -e


TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/blfs-sources}
BUILDDIR=${BUILDDIR:-$(dirname $0)/build}

name=libtirpc
version=1.2.6

rm -fr $TMP
mkdir -p $TMP $LOG $SRC $BUILDDIR

tar xf $SRC/$name-$version.tar.* -C $TMP
 
{ time \
   {

    cd $TMP/$name-$version

	./configure --prefix=/usr                                   \
				--sysconfdir=/etc                               \
				--disable-static                                \
				--disable-gssapi
	make

	make install
	mv -v /usr/lib/libtirpc.so.* /lib
	ln -sfv ../../lib/libtirpc.so.3.0.0 /usr/lib/libtirpc.so

    }
} 2>&1 | tee $LOG/$name.log

[ $PIPESTATUS = 0 ] && echo "$name-$version" > $BUILDDIR/$name || exit $PIPESTATUS

rm -fr $TMP 
