#!/bin/bash 
set -e
 
TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/blfs-sources}
BUILDLOG=${BUILDLOG:-$(dirname $0)/build}
 
name=libxml2
version=2.9.10
_version=20130923
 
rm -fr $TMP
mkdir -p $TMP $LOG $SRC  $BUILDLOG
 
tar xf $SRC/$name-$version.tar.* -C $TMP
 
{ time \
   {
 
    cd $TMP/$name-$version

    sed -i 's/test.test/#&/' python/tests/tstLastError.py

    ./configure --prefix=/usr    \
	    --disable-static \
	    --with-history   \
	    --with-icu       \
	    --with-threads   \
	    --with-python=/usr/bin/python3
    make

    tar xf $SRC/xmlts$_version.tar.gz

    make install

    }   
} 2>&1 | tee $LOG/$name.log
    
[ $PIPESTATUS = 0 ] && echo "$name-$version" > $BUILDLOG/$name || exit $PIPESTATUS

rm -fr $TMP	
	

