#!/bin/bash 
set -e
 
TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/blfs-sources}
BUILDLOG=${BUILDLOG:-$(dirname $0)/build}
 
name=links
version=2.20.2
 
rm -fr $TMP
mkdir -p $TMP $LOG $SRC  $BUILDLOG
 
tar xf $SRC/$name-$version.tar.* -C $TMP
 
{ time \
   {
 
    cd $TMP/$name-$version

	./configure --prefix=/usr    \
		--mandir=/usr/share/man  
#		--enable-graphics
	make

	make install
	install -v -d -m755 /usr/share/doc/links-$version
	install -v -m644 doc/links_cal/* KEYS BRAILLE_HOWTO \
	    /usr/share/doc/links-$version


    }   
} 2>&1 | tee $LOG/$name.log
    
[ $PIPESTATUS = 0 ] && echo "$name-$version" > $BUILDLOG/$name || exit $PIPESTATUS

rm -fr $TMP	
	

