#!/bin/bash 
set -e
 
TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/blfs-sources}
BUILDLOG=${BUILDLOG:-$(dirname $0)/build}
 
name=LVM2
version=2.03.09
 
rm -fr $TMP
mkdir -p $TMP $LOG $SRC  $BUILDLOG
 
tar xf $SRC/$name.$version.tgz -C $TMP
 
{ time \
   {
 
    cd $TMP/$name.$version

	SAVEPATH=$PATH
	PATH=$PATH:/sbin:/usr/sbin
	./configure --prefix=/usr       \
				--exec-prefix=      \
				--enable-cmdlib     \
				--enable-pkgconfig  \
				--enable-udev_sync
	make
	PATH=$SAVEPATH
	unset SAVEPATH

	make install

    }   
} 2>&1 | tee $LOG/$name.log
    
[ $PIPESTATUS = 0 ] && echo "$name-$version" > $BUILDLOG/$name || exit $PIPESTATUS

rm -fr $TMP	
	

