#!/bin/bash 
set -e
 
TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/blfs-sources}
BUILDLOG=${BUILDLOG:-$(dirname $0)/build}

pkgbase=make-ca-pass2
name=make-ca
version=1.7
 
rm -fr $TMP
mkdir -p $TMP $LOG $SRC  $BUILDLOG
 
tar xf $SRC/$name-$version.tar.* -C $TMP
 
{ time \
   {
 
    cd $TMP/$name-$version

	make install
	install -vdm755 /etc/ssl/local

	/usr/sbin/make-ca -g
	systemctl enable update-pki.timer
	openssl x509 -in $SRC/root.crt -text -fingerprint -setalias "CAcert Class 1 root" \
			-addtrust serverAuth -addtrust emailProtection -addtrust codeSigning \
			> /etc/ssl/local/CAcert_Class_1_root.pem
	openssl x509 -in $SRC/class3.crt -text -fingerprint -setalias "CAcert Class 3 root" \
			-addtrust serverAuth -addtrust emailProtection -addtrust codeSigning \
			> /etc/ssl/local/CAcert_Class_3_root.pem
	/usr/sbin/make-ca -r -f


    }   
} 2>&1 | tee $LOG/$pkgbase.log
    
[ $PIPESTATUS = 0 ] && echo "$name-$version" > $BUILDLOG/$pkgbase || exit $PIPESTATUS

rm -fr $TMP	
	

