#!/bin/bash 
set -e
 
TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/blfs-sources}
BUILDLOG=${BUILDLOG:-$(dirname $0)/build}
 
name=nss
version=3.54
 
rm -fr $TMP
mkdir -p $TMP $LOG $SRC  $BUILDLOG
 
tar xf $SRC/$name-$version.tar.* -C $TMP
 
{ time \
   {
 
    cd $TMP/$name-$version

	patch -Np1 -i $SRC/nss-$version-standalone-2.patch

	cd nss

	make BUILD_OPT=1                        \
		NSPR_INCLUDE_DIR=/usr/include/nspr  \
		USE_SYSTEM_ZLIB=1                   \
		ZLIB_LIBS=-lz                       \
		NSS_ENABLE_WERROR=0                 \
		$([ $(uname -m) = x86_64 ] && echo USE_64=1) \
		$([ -f /usr/include/sqlite3.h ] && echo NSS_USE_SYSTEM_SQLITE=1)

	cd ../dist

	install -v -m755 Linux*/lib/*.so              /usr/lib
	install -v -m644 Linux*/lib/{*.chk,libcrmf.a} /usr/lib

	install -v -m755 -d                           /usr/include/nss
	cp -v -RL {public,private}/nss/*              /usr/include/nss
	chmod -v 644                                  /usr/include/nss/*

	install -v -m755 Linux*/bin/{certutil,nss-config,pk12util} /usr/bin

	install -v -m644 Linux*/lib/pkgconfig/nss.pc  /usr/lib/pkgconfig

    }   
} 2>&1 | tee $LOG/$name.log
    
[ $PIPESTATUS = 0 ] && echo "$name-$version" > $BUILDLOG/$name || exit $PIPESTATUS

rm -fr $TMP	
	

