#!/bin/bash  -e


TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/blfs-sources}
BUILDDIR=${BUILDDIR:-$(dirname $0)/build}

name=ntfs-3g
version=2017.3.23

rm -fr $TMP
mkdir -p $TMP $LOG $SRC $BUILDDIR

tar xf $SRC/${name}_ntfsprogs-$version.tgz -C $TMP

{ time \
   {

    cd $TMP/${name}_ntfsprogs-$version

    ./configure --prefix=/usr        \
                --disable-static     \
                --with-fuse=internal \
                --docdir=/usr/share/doc/$name-$version
    make

    make install
    ln -sv ../bin/ntfs-3g /sbin/mount.ntfs
    ln -sv ntfs-3g.8 /usr/share/man/man8/mount.ntfs.8

    chmod -v 4755 /bin/ntfs-3g

    }
} 2>&1 | tee $LOG/$name.log

[ $PIPESTATUS = 0 ] && echo "$name-$version" > $BUILDDIR/$name || exit $PIPESTATUS

rm -fr $TMP 
