#!/bin/bash  -e


TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/blfs-sources}
BUILDDIR=${BUILDDIR:-$(dirname $0)/build}

pkgbase=openldap-pass2
name=openldap
version=2.4.50

rm -fr $TMP
mkdir -p $TMP $LOG $SRC $BUILDDIR

tar xf $SRC/$name-$version.tgz -C $TMP
 
{ time \
   {

    cd $TMP/$name-$version

	patch -Np1 -i $SRC/openldap-$version-consolidated-1.patch
	autoconf

	./configure --prefix=/usr         \
				--sysconfdir=/etc     \
				--localstatedir=/var  \
				--libexecdir=/usr/lib \
				--disable-static      \
				--disable-debug       \
				--with-tls=openssl    \
				--with-cyrus-sasl     \
				--enable-dynamic      \
				--enable-crypt        \
				--enable-spasswd      \
				--enable-slapd        \
				--enable-modules      \
				--enable-rlookups     \
				--enable-backends=mod \
				--disable-ndb         \
				--disable-sql         \
				--disable-shell       \
				--disable-bdb         \
				--disable-hdb         \
				--enable-overlays=mod

	make depend
	make

	make install

	sed -e "s/\.la/.so/" -i /etc/openldap/slapd.{conf,ldif}{,.default}

	install -v -dm700 -o ldap -g ldap /var/lib/openldap

	install -v -dm700 -o ldap -g ldap /etc/openldap/slapd.d
	chmod   -v    640     /etc/openldap/slapd.{conf,ldif}
	chown   -v  root:ldap /etc/openldap/slapd.{conf,ldif}

	install -v -dm755 /usr/share/doc/openldap-$version
	cp      -vfr      doc/{drafts,rfc,guide} \
					  /usr/share/doc/openldap-$version


    }
} 2>&1 | tee $LOG/$pkgbase.log

[ $PIPESTATUS = 0 ] && echo "$name-$version" > $BUILDDIR/$pkgbase || exit $PIPESTATUS

rm -fr $TMP 
