#!/bin/bash  -e


TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/blfs-sources}
BUILDDIR=${BUILDDIR:-$(dirname $0)/build}

pkgbase=openldap-pass1
name=openldap
version=2.4.50

rm -fr $TMP
mkdir -p $TMP $LOG $SRC $BUILDDIR

tar xf $SRC/$name-$version.tgz -C $TMP
 
{ time \
   {

    cd $TMP/$name-$version

	groupadd -g 83 ldap
	useradd  -c "OpenLDAP Daemon Owner" \
			 -d /var/lib/openldap -u 83 \
			 -g ldap -s /bin/false ldap

	patch -Np1 -i $SRC/openldap-$version-consolidated-1.patch
	autoconf

	./configure --prefix=/usr         \
				--sysconfdir=/etc     \
				--localstatedir=/var  \
				--libexecdir=/usr/lib \
				--disable-static      \
				--disable-debug       \
				--with-tls=openssl    \
				--enable-dynamic      \
				--enable-slapd        \
				--enable-modules      \
				--enable-rlookups     \
				--enable-backends=mod \
				--disable-ndb         \
				--disable-sql         \
				--disable-shell       \
				--disable-bdb         \
				--disable-hdb         \
				--enable-overlays=mod

	make depend
	make

	make install



    }
} 2>&1 | tee $LOG/$pkgbase.log

[ $PIPESTATUS = 0 ] && echo "$name-$version" > $BUILDDIR/$pkgbase || exit $PIPESTATUS

rm -fr $TMP 
