#!/bin/bash 
set -e
 
TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/blfs-sources}
BUILDLOG=${BUILDLOG:-$(dirname $0)/build}

pkgbase=p11-kit-pass2
name=p11-kit
version=0.23.20
 
rm -fr $TMP
mkdir -p $TMP $LOG $SRC  $BUILDLOG
 
tar xf $SRC/$name-$version.tar.* -C $TMP
 
{ time \
   {
 
    cd $TMP/$name-$version

    sed '20,$ d' -i trust/trust-extract-compat.in
	cat >> trust/trust-extract-compat.in << "EOF"
# Copy existing anchor modifications to /etc/ssl/local
/usr/libexec/make-ca/copy-trust-modifications

# Generate a new trust store
/usr/sbin/make-ca -f -g
EOF

	./configure --prefix=/usr     \
		--sysconfdir=/etc         \
		--enable-doc              \
		--with-hash-impl=freebl   \
		--with-trust-paths=/etc/pki/anchors

	make

	make install

	ln -sfv /usr/libexec/p11-kit/trust-extract-compat \
		/usr/bin/update-ca-certificates
   
   ln -sfv ./pkcs11/p11-kit-trust.so /usr/lib/libnssckbi.so

	}   
} 2>&1 | tee $LOG/$pkgbase.log
    
[ $PIPESTATUS = 0 ] && echo "$name-$version" > $BUILDLOG/$pkgbase || exit $PIPESTATUS

rm -fr $TMP	
	

