#!/bin/bash 
set -e
 
TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/blfs-sources}
BUILDLOG=${BUILDLOG:-$(dirname $0)/build}
 
name=pcre
version=8.44
 
rm -fr $TMP
mkdir -p $TMP $LOG $SRC  $BUILDLOG
 
tar xf $SRC/$name-$version.tar.* -C $TMP
 
{ time \
   {
 
    cd $TMP/$name-$version

	./configure --prefix=/usr                     \
				--docdir=/usr/share/doc/pcre-$version \
				--enable-unicode-properties       \
				--enable-pcre16                   \
				--enable-pcre32                   \
				--enable-pcregrep-libz            \
				--enable-pcregrep-libbz2          \
				--enable-pcretest-libreadline     \
				--disable-static                  \
				--with-pcre=system                \
				--enable-jit
	make

	make install
	mv -v /usr/lib/libpcre.so.* /lib
	ln -sfv ../../lib/$(readlink /usr/lib/libpcre.so) /usr/lib/libpcre.so

    }   
} 2>&1 | tee $LOG/$name.log
    
[ $PIPESTATUS = 0 ] && echo "$name-$version" > $BUILDLOG/$name || exit $PIPESTATUS

rm -fr $TMP	
	

