#!/bin/bash  -e


TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/blfs-sources}
BUILDDIR=${BUILDDIR:-$(dirname $0)/build}

name=polkit
version=32450615

rm -fr $TMP
mkdir -p $TMP $LOG $SRC $BUILDDIR

tar xf $SRC/$name-$version.tar.* -C $TMP
 
{ time \
   {

    cd $TMP/$name-$version

	groupadd -fg 27 polkitd
	useradd -c "PolicyKit Daemon Owner" -d /etc/polkit-1 -u 27 \
	        -g polkitd -s /bin/false polkitd

	sed -i "s:/sys/fs/cgroup/systemd/:/sys:g" configure

	./configure --prefix=/usr    \
            --sysconfdir=/etc    \
            --localstatedir=/var \
            --disable-static     \
            --with-os-type=LFS   \
			--enable-gtk-doc     \
			
	make

	make install

	cat > /etc/pam.d/polkit-1 << "EOF"
# Begin /etc/pam.d/polkit-1

auth     include        system-auth
account  include        system-account
password include        system-password
session  include        system-session

# End /etc/pam.d/polkit-1
EOF

    }
} 2>&1 | tee $LOG/$name.log

[ $PIPESTATUS = 0 ] && echo "$name-$version" > $BUILDDIR/$name || exit $PIPESTATUS

rm -fr $TMP 
