#!/bin/bash  -e


TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/blfs-sources}
BUILDDIR=${BUILDDIR:-$(dirname $0)/build}

pkgbase=pycairo-python3
name=pycairo
version=1.19.1

rm -fr $TMP
mkdir -p $TMP $LOG $SRC $BUILDDIR

tar xf $SRC/$name-$version.tar.* -C $TMP
 
{ time \
   {

    cd $TMP/$name-$version

	python3 setup.py build

	python3 setup.py install --optimize=1   
	python3 setup.py install_pycairo_header 
	python3 setup.py install_pkgconfig

    }
} 2>&1 | tee $LOG/$pkgbase.log

[ $PIPESTATUS = 0 ] && echo "$name-$version" > $BUILDDIR/$pkgbase || exit $PIPESTATUS

rm -fr $TMP 
