#!/bin/bash  -e


TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/blfs-sources}
BUILDDIR=${BUILDDIR:-$(dirname $0)/build}

pkgbase=pygobject-python3
name=pygobject
version=3.36.1

rm -fr $TMP
mkdir -p $TMP $LOG $SRC $BUILDDIR

tar xf $SRC/$name-$version.tar.* -C $TMP
 
{ time \
   {

    cd $TMP/$name-$version

	mkdir python3                             
	pushd python3                             
	meson --prefix=/usr -Dpython=python3 .. 
	ninja                                   
	popd

	ninja -C python3 install

    }
} 2>&1 | tee $LOG/$pkgbase.log

[ $PIPESTATUS = 0 ] && echo "$name-$version" > $BUILDDIR/$pkgbase || exit $PIPESTATUS

rm -fr $TMP 
