#!/bin/bash 
set -e
 
TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/blfs-sources}
BUILDLOG=${BUILDLOG:-$(dirname $0)/build}
 
name=sgml-common
version=0.6.3
 
rm -fr $TMP
mkdir -p $TMP $LOG $SRC  $BUILDLOG
 
tar xf $SRC/$name-$version.tgz -C $TMP
 
{ time \
   {
 
    cd $TMP/$name-$version

    patch -Np1 -i $SRC/$name-$version-manpage-1.patch
    autoreconf -f -i

    ./configure --prefix=/usr --sysconfdir=/etc

    make

    make docdir=/usr/share/doc install

    install-catalog --add /etc/sgml/sgml-ent.cat \
	     /usr/share/sgml/sgml-iso-entities-8879.1986/catalog

    install-catalog --add /etc/sgml/sgml-docbook.cat \
	    /etc/sgml/sgml-ent.cat

    }   
} 2>&1 | tee $LOG/$name.log
    
[ $PIPESTATUS = 0 ] && echo "$name-$version" > $BUILDLOG/$name || exit $PIPESTATUS

rm -fr $TMP	
	

