#!/bin/bash  -e


TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/blfs-sources}
BUILDDIR=${BUILDDIR:-$(dirname $0)/build}

name=systemd
version=245

rm -fr $TMP
mkdir -p $TMP $LOG $SRC $BUILDDIR

tar xf $SRC/$name-$version.tar.* -C $TMP
 
{ time \
   {

    cd $TMP/$name-$version

    patch -Np1 -i $SRC/systemd-$version-gcc_10-fixes-2.patch

    sed -i 's/GROUP="render", //' rules.d/50-udev-default.rules.in

    mkdir build
	cd    build

	meson --prefix=/usr                 \
	      --sysconfdir=/etc             \
	      --localstatedir=/var          \
	      -Dblkid=true                  \
	      -Dbuildtype=release           \
	      -Ddefault-dnssec=no           \
	      -Dfirstboot=false             \
	      -Dinstall-tests=false         \
	      -Dldconfig=false              \
	      -Dman=auto                    \
	      -Drootprefix=                 \
	      -Drootlibdir=/lib             \
	      -Dsplit-usr=true              \
	      -Dsysusers=false              \
	      -Drpmmacrosdir=no             \
	      -Db_lto=false                 \
	      -Dhomed=true                  \
	      -Duserdb=true                 \
          -Dlz4=true                    \
          -Dgnu-efi=true                \
          -Dlibidn2=true                \
	      ..

	ninja

	ninja install

	cat >> /etc/pam.d/system-session << "EOF"
# Begin Systemd addition
    
session  required    pam_loginuid.so
session  optional    pam_systemd.so

# End Systemd addition
EOF

	cat > /etc/pam.d/systemd-user << "EOF"
# Begin /etc/pam.d/systemd-user

account  required    pam_access.so
account  include     system-account

session  required    pam_env.so
session  required    pam_limits.so
session  required    pam_unix.so
session  required    pam_loginuid.so
session  optional    pam_keyinit.so force revoke
session  optional    pam_systemd.so

auth     required    pam_deny.so
password required    pam_deny.so

# End /etc/pam.d/systemd-user
EOF

    }
} 2>&1 | tee $LOG/$name.log

[ $PIPESTATUS = 0 ] && echo "$name-$version" > $BUILDDIR/$name || exit $PIPESTATUS

rm -fr $TMP 
