#!/bin/bash 
set -e
 
TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/blfs-sources}
BUILDLOG=${BUILDLOG:-$(dirname $0)/build}
 
name=unifont
version=13.0.02
 
rm -fr $TMP
mkdir -p $TMP $LOG $SRC  $BUILDLOG
 
{ time \
   {
 
    mkdir -pv /usr/share/fonts/unifont
    gunzip -c $SRC/unifont-$version.pcf.gz > \
     /usr/share/fonts/unifont/unifont.pcf

    }   
} 2>&1 | tee $LOG/$name.log
    
[ $PIPESTATUS = 0 ] && echo "$name-$version" > $BUILDLOG/$name || exit $PIPESTATUS

rm -fr $TMP	
	

