#!/bin/bash 
set -e
 
TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/home/blfs-sources}
BUILDLOG=${BUILDLOG:-$(dirname $0)/build}
 
name=unzip
version=60
_version=6.0
 
rm -fr $TMP
mkdir -p $TMP $LOG $SRC  $BUILDLOG
 
tar xf $SRC/$name$version.tar.* -C $TMP
 
{ time \
   {
 
    cd $TMP/$name$version

    patch -Np1 -i $SRC/unzip-$_version-consolidated_fixes-1.patch

    make -f unix/Makefile generic

    make prefix=/usr MANDIR=/usr/share/man/man1 \
	    -f unix/Makefile install

    }   
} 2>&1 | tee $LOG/$name.log
    
[ $PIPESTATUS = 0 ] && echo "$name-$version" > $BUILDLOG/$name || exit $PIPESTATUS

rm -fr $TMP	
	

