#!/bin/bash
set -e

TMP=${TMP:-$(dirname $0)/Build-TMP}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-$LFS/sources}

mkdir -pv $TMP $LOG

pkgname=findutils
pkgver=4.7.0

tar xf $SRC/$pkgname-$pkgver.tar.xz -C $TMP

{ time \
   {
    
    cd $TMP/$pkgname-$pkgver
    ./configure --prefix=/usr               \
                --host=$LFS_TGT             \
                --build=$(build-aux/config.guess)
    make
    make DESTDIR=$LFS install
    mv -v $LFS/usr/bin/find $LFS/bin
    sed -i 's|find:=${BINDIR}|find:=/bin|' $LFS/usr/bin/updatedb

    }
} 2>&1 | tee $pkgname.log

[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
