#!/bin/bash
set -e

TMP=${TMP:-$(dirname $0)/Build-TMP}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-$LFS/sources}

mkdir -pv $TMP $LOG

pkgname=grep
pkgver=3.5

tar xf $SRC/$pkgname-$pkgver.tar.xz -C $TMP

{ time \
   {
    
    cd $TMP/$pkgname-$pkgver
    ./configure --prefix=/usr               \
                --host=$LFS_TGT             \
                --bindir=/bin
    make
    make DESTDIR=$LFS install

    }
} 2>&1 | tee $pkgname.log
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS
rm -fr $TMP
