#!/bin/bash 
set -e


TMP=${TMP:-$/tmp}
LOG=${LOG:-$HOME/logs/stage}
SRC=${SRC:-$LFS/sources}

pkgname=
pkgver=

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/$pkgname-$pkgver.tar.xz -C $TMP

{ time \
   {

    cd $TMP/$pkgname-$pkgver
    


    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
