#!/bin/bash
set -e

TMP=${TMP:-/tmp}
LOG=${LOG:-$HOME/logs/stage1}
SRC=${SRC:-$LFS/sources}

mkdir -pv $TMP $LOG

pkgname=binutils-pass2
pkgver=2.36

tar xf $SRC/binutils-$pkgver.tar.xz -C $TMP

{ time \
   {
    
    cd $TMP/binutils-$pkgver

    mkdir -v build
    cd       build

  ../configure                   \
      --prefix=/usr              \
      --build=$(../config.guess) \
      --host=$LFS_TGT            \
      --disable-nls              \
      --enable-shared            \
      --disable-werror           \
      --enable-64-bit-bfd

    make
    
    make DESTDIR=$LFS install

    }
} 2>&1 | tee $pkgname.log

[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
