#!/bin/bash
set -e

TMP=${TMP:-/tmp}
LOG=${LOG:-$HOME/logs/stage1}
SRC=${SRC:-$LFS/sources}

mkdir -pv $TMP $LOG

pkgname=file
pkgver=5.39

tar xf $SRC/$pkgname-$pkgver.tar.gz -C $TMP

{ time \
   {
    
    cd $TMP/$pkgname-$pkgver

	mkdir build
	pushd build
	  ../configure
	  make
	popd

    ./configure --prefix=/usr --host=$LFS_TGT --build=$(./config.guess)

    make FILE_COMPILE=$(pwd)/build/src/file
    
    make DESTDIR=$LFS install

    }
} 2>&1 | tee $pkgname.log

[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
