#!/bin/bash
set -e

TMP=${TMP:-/tmp}
LOG=${LOG:-$HOME/logs/stage1}
SRC=${SRC:-$LFS/sources}

mkdir -pv $TMP $LOG

name=gawk
version=5.1.0

tar xf $SRC/$name-$version.tar.xz -C $TMP

{ time \
   {
    
    cd $TMP/$name-$version

    sed -i 's/extras//' Makefile.in

	./configure --prefix=/usr   \
	            --host=$LFS_TGT \
	            --build=$(./config.guess)

    make
    
    make DESTDIR=$LFS install

    }
} 2>&1 | tee $name.log

[ $PIPESTATUS = 0 ] && mv $name.log $LOG || exit $PIPESTATUS

rm -fr $TMP
