#!/bin/bash
set -e

TMP=${TMP:-/tmp}
LOG=${LOG:-$HOME/logs/stage1}
SRC=${SRC:-$LFS/sources}

mkdir -pv $TMP $LOG

pkgname=make
pkgver=4.3

tar xf $SRC/$pkgname-$pkgver.tar.gz -C $TMP

{ time \
   {
    
    cd $TMP/$pkgname-$pkgver

	./configure --prefix=/usr   \
	            --without-guile \
	            --host=$LFS_TGT \
	            --build=$(build-aux/config.guess)

    make
    
    make DESTDIR=$LFS install

    }
} 2>&1 | tee $pkgname.log

[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
