#!/bin/bash
set -e

TMP=${TMP:-/tmp}
LOG=${LOG:-$HOME/logs/stage1}
SRC=${SRC:-$LFS/sources}

mkdir -pv $TMP $LOG

name=make
version=4.3

tar xf $SRC/$name-$version.tar.gz -C $TMP

{ time \
   {
    
    cd $TMP/$name-$version

	./configure --prefix=/usr   \
	            --without-guile \
	            --host=$LFS_TGT \
	            --build=$(build-aux/config.guess)

    make
    
    make DESTDIR=$LFS install

    }
} 2>&1 | tee $name.log

[ $PIPESTATUS = 0 ] && mv $name.log $LOG || exit $PIPESTATUS

rm -fr $TMP
