#!/bin/bash
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-$LFS/sources}

mkdir -pv $TMP $LOG

pkgname=tar
pkgver=1.32

tar xf $SRC/$pkgname-$pkgver.tar.xz -C $TMP

{ time \
   {
    
    cd $TMP/$pkgname-$pkgver
    ./configure --prefix=/usr                                 \
                --host=$LFS_TGT                               \
                --build=$(build-aux/config.guess)             \
                --bindir=/bin
    make
    make DESTDIR=$LFS install

    }
} 2>&1 | tee $pkgname.log

[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
