#!/bin/bash
set -e

TMP=${TMP:-/tmp}
LOG=${LOG:-$HOME/logs/stage1}
SRC=${SRC:-$LFS/sources}

mkdir -pv $TMP $LOG

pkgname=tar
pkgver=1.33

tar xf $SRC/$pkgname-$pkgver.tar.xz -C $TMP

{ time \
   {
    
    cd $TMP/$pkgname-$pkgver

	./configure --prefix=/usr                     \
	            --host=$LFS_TGT                   \
	            --build=$(build-aux/config.guess) \
	            --bindir=/bin

    make
    
    make DESTDIR=$LFS install

    }
} 2>&1 | tee $pkgname.log

[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
