#!/bin/bash
set -e

TMP=${TMP:-/tmp}
LOG=${LOG:-$HOME/logs/stage1}
SRC=${SRC:-$LFS/sources}

mkdir -pv $TMP $LOG

pkgname=zlib
pkgver=1.2.11

tar xf $SRC/$pkgname-$pkgver.tar.xz -C $TMP

{ time \
   {
    
    cd $TMP/$pkgname-$pkgver

    ./configure --prefix=/usr

    make
    
    make DESTDIR=$LFS install
    mv -v $LFS/usr/lib/libz.so.* $LFS/lib
    ln -sfv ../../lib/$(readlink $LFS/usr/lib/libz.so) $LFS/usr/lib/libz.so

    }
} 2>&1 | tee $pkgname.log

[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
