#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/sources}

pkgname=libcap
pkgver=2.44

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/$pkgname-$pkgver.tar.xz -C $TMP

{ time \
   {

    cd $TMP/$pkgname-$pkgver
    
    sed -i '/install -m.*STACAPLIBNAME/d' libcap/Makefile
    
    make lib=lib
    
    make lib=lib PKGCONFIGDIR=/usr/lib/pkgconfig install
    chmod -v 755 /lib/libcap.so.2.44
    mv -v /lib/libpsx.a /usr/lib
    rm -v /lib/libcap.so
    ln -sfv ../../lib/libcap.so.2 /usr/lib/libcap.so

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
