#!/bin/bash 
set -e

TMP=${TMP:-$(mktemp -d)}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/sources}

pkgname=perl
pkgver=5.32.0

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/$pkgname-$pkgver.tar.xz -C $TMP

{ time \
   {

    cd $TMP/$pkgname-$pkgver

export BUILD_ZLIB=False
export BUILD_BZIP2=0

sh Configure -des                                                  \
             -Dprefix=/usr                                         \
             -Dvendorprefix=/usr                                   \
             -Dprivlib=/usr/lib/perl5/${pkgver:0:4}/core_perl      \
             -Darchlib=/usr/lib/perl5/${pkgver:0:4}/core_perl      \
             -Dsitelib=/usr/lib/perl5/${pkgver:0:4}/site_perl      \
             -Dsitearch=/usr/lib/perl5/${pkgver:0:4}/site_perl     \
             -Dvendorlib=/usr/lib/perl5/${pkgver:0:4}/vendor_perl  \
             -Dvendorarch=/usr/lib/perl5/${pkgver:0:4}/vendor_perl \
             -Dman1dir=/usr/share/man/man1                         \
             -Dman3dir=/usr/share/man/man3                         \
             -Dpager="/usr/bin/less -isR"                          \
             -Duseshrplib                                          \
             -Dusethreads

    make

    make install
    unset BUILD_ZLIB BUILD_BZIP2
    
    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
