#!/bin/bash 
set -e


TMP=${TMP:-$(dirname $0)/Build-TMP}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-/sources}

pkgname=tcl
pkgver=8.6.10

rm -fr $TMP
mkdir -p $TMP $LOG

tar xf $SRC/$pkgname$pkgver-src.tar.gz -C $TMP

{ time \
   {

    cd $TMP/$pkgname$pkgver

    tar -xf $SRC/tcl$pkgver-html.tar.gz --strip-components=1

    SRCDIR=$(pwd)
    cd unix
    ./configure --prefix=/usr           \
                --mandir=/usr/share/man \
                $([ "$(uname -m)" = x86_64 ] && echo --enable-64bit)

    make

    sed -e "s|$SRCDIR/unix|/usr/lib|" \
        -e "s|$SRCDIR|/usr/include|"  \
        -i tclConfig.sh

    sed -e "s|$SRCDIR/unix/pkgs/tdbc1.1.1|/usr/lib/tdbc1.1.1|" \
        -e "s|$SRCDIR/pkgs/tdbc1.1.1/generic|/usr/include|"    \
        -e "s|$SRCDIR/pkgs/tdbc1.1.1/library|/usr/lib/tcl8.6|" \
        -e "s|$SRCDIR/pkgs/tdbc1.1.1|/usr/include|"            \
        -i pkgs/tdbc1.1.1/tdbcConfig.sh

    sed -e "s|$SRCDIR/unix/pkgs/itcl4.2.0|/usr/lib/itcl4.2.0|" \
        -e "s|$SRCDIR/pkgs/itcl4.2.0/generic|/usr/include|"    \
        -e "s|$SRCDIR/pkgs/itcl4.2.0|/usr/include|"            \
        -i pkgs/itcl4.2.0/itclConfig.sh

    unset SRCDIR

    make install

    chmod -v u+w /usr/lib/libtcl${pkgver:0:3}.so

    make install-private-headers

    ln -sfv tclsh${pkgver:0:3} /usr/bin/tclsh

    mv /usr/share/man/man3/{Thread,Tcl_Thread}.3

    }
} 2>&1 | tee $pkgname.log
    
[ $PIPESTATUS = 0 ] && mv $pkgname.log $LOG || exit $PIPESTATUS

rm -fr $TMP
